using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Text;
using System.Security.Permissions;
using System.Windows.Forms.Layout;

namespace System.Windows.Forms
{
	/// <summary>Handles the painting functionality for <see cref="T:System.Windows.Forms.ToolStrip" /> objects.</summary>
	// Token: 0x020003E8 RID: 1000
	public abstract class ToolStripRenderer
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Windows.Forms.ToolStripRenderer" /> class. </summary>
		// Token: 0x0600431A RID: 17178 RVA: 0x001203AD File Offset: 0x0011E5AD
		protected ToolStripRenderer()
		{
		}

		// Token: 0x0600431B RID: 17179 RVA: 0x001203C0 File Offset: 0x0011E5C0
		internal ToolStripRenderer(bool isAutoGenerated)
		{
			this.isAutoGenerated = isAutoGenerated;
		}

		// Token: 0x170010DC RID: 4316
		// (get) Token: 0x0600431C RID: 17180 RVA: 0x001203DC File Offset: 0x0011E5DC
		private static ColorMatrix DisabledImageColorMatrix
		{
			get
			{
				if (ToolStripRenderer.disabledImageColorMatrix == null)
				{
					float[][] array = new float[5][];
					array[0] = new float[]
					{
						0.2125f,
						0.2125f,
						0.2125f,
						0f,
						0f
					};
					array[1] = new float[]
					{
						0.2577f,
						0.2577f,
						0.2577f,
						0f,
						0f
					};
					array[2] = new float[]
					{
						0.0361f,
						0.0361f,
						0.0361f,
						0f,
						0f
					};
					float[][] array2 = array;
					int num = 3;
					float[] array3 = new float[5];
					array3[3] = 1f;
					array2[num] = array3;
					array[4] = new float[]
					{
						0.38f,
						0.38f,
						0.38f,
						0f,
						1f
					};
					float[][] array4 = new float[5][];
					float[][] array5 = array4;
					int num2 = 0;
					float[] array6 = new float[5];
					array6[0] = 1f;
					array5[num2] = array6;
					float[][] array7 = array4;
					int num3 = 1;
					float[] array8 = new float[5];
					array8[1] = 1f;
					array7[num3] = array8;
					float[][] array9 = array4;
					int num4 = 2;
					float[] array10 = new float[5];
					array10[2] = 1f;
					array9[num4] = array10;
					float[][] array11 = array4;
					int num5 = 3;
					float[] array12 = new float[5];
					array12[3] = 0.7f;
					array11[num5] = array12;
					array4[4] = new float[5];
					ToolStripRenderer.disabledImageColorMatrix = ControlPaint.MultiplyColorMatrix(array4, array);
				}
				return ToolStripRenderer.disabledImageColorMatrix;
			}
		}

		// Token: 0x170010DD RID: 4317
		// (get) Token: 0x0600431D RID: 17181 RVA: 0x001204C0 File Offset: 0x0011E6C0
		private EventHandlerList Events
		{
			get
			{
				if (this.events == null)
				{
					this.events = new EventHandlerList();
				}
				return this.events;
			}
		}

		// Token: 0x170010DE RID: 4318
		// (get) Token: 0x0600431E RID: 17182 RVA: 0x001204DB File Offset: 0x0011E6DB
		internal bool IsAutoGenerated
		{
			get
			{
				return this.isAutoGenerated;
			}
		}

		// Token: 0x170010DF RID: 4319
		// (get) Token: 0x0600431F RID: 17183 RVA: 0x0000DE5C File Offset: 0x0000C05C
		internal virtual ToolStripRenderer RendererOverride
		{
			get
			{
				return null;
			}
		}

		/// <summary>Occurs when an arrow on a <see cref="T:System.Windows.Forms.ToolStripItem" /> is rendered.</summary>
		// Token: 0x14000363 RID: 867
		// (add) Token: 0x06004320 RID: 17184 RVA: 0x001204E3 File Offset: 0x0011E6E3
		// (remove) Token: 0x06004321 RID: 17185 RVA: 0x001204F1 File Offset: 0x0011E6F1
		public event ToolStripArrowRenderEventHandler RenderArrow
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderArrow, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderArrow, value);
			}
		}

		/// <summary>Occurs when the background for a <see cref="T:System.Windows.Forms.ToolStrip" /> is rendered.</summary>
		// Token: 0x14000364 RID: 868
		// (add) Token: 0x06004322 RID: 17186 RVA: 0x001204FF File Offset: 0x0011E6FF
		// (remove) Token: 0x06004323 RID: 17187 RVA: 0x0012050D File Offset: 0x0011E70D
		public event ToolStripRenderEventHandler RenderToolStripBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderToolStripBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderToolStripBackground, value);
			}
		}

		/// <summary>Draws the background of a <see cref="T:System.Windows.Forms.ToolStripPanel" />.</summary>
		// Token: 0x14000365 RID: 869
		// (add) Token: 0x06004324 RID: 17188 RVA: 0x0012051B File Offset: 0x0011E71B
		// (remove) Token: 0x06004325 RID: 17189 RVA: 0x00120529 File Offset: 0x0011E729
		public event ToolStripPanelRenderEventHandler RenderToolStripPanelBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderToolStripPanelBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderToolStripPanelBackground, value);
			}
		}

		/// <summary>Draws the background of a <see cref="T:System.Windows.Forms.ToolStripContentPanel" />.</summary>
		// Token: 0x14000366 RID: 870
		// (add) Token: 0x06004326 RID: 17190 RVA: 0x00120537 File Offset: 0x0011E737
		// (remove) Token: 0x06004327 RID: 17191 RVA: 0x00120545 File Offset: 0x0011E745
		public event ToolStripContentPanelRenderEventHandler RenderToolStripContentPanelBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderToolStripContentPanelBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderToolStripContentPanelBackground, value);
			}
		}

		/// <summary>Occurs when the border for a <see cref="T:System.Windows.Forms.ToolStrip" /> is rendered.</summary>
		// Token: 0x14000367 RID: 871
		// (add) Token: 0x06004328 RID: 17192 RVA: 0x00120553 File Offset: 0x0011E753
		// (remove) Token: 0x06004329 RID: 17193 RVA: 0x00120561 File Offset: 0x0011E761
		public event ToolStripRenderEventHandler RenderToolStripBorder
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderBorder, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderBorder, value);
			}
		}

		/// <summary>Occurs when the background for a <see cref="T:System.Windows.Forms.ToolStripButton" /> is rendered</summary>
		// Token: 0x14000368 RID: 872
		// (add) Token: 0x0600432A RID: 17194 RVA: 0x0012056F File Offset: 0x0011E76F
		// (remove) Token: 0x0600432B RID: 17195 RVA: 0x0012057D File Offset: 0x0011E77D
		public event ToolStripItemRenderEventHandler RenderButtonBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderButtonBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderButtonBackground, value);
			}
		}

		/// <summary>Occurs when the background for a <see cref="T:System.Windows.Forms.ToolStripDropDownButton" /> is rendered.</summary>
		// Token: 0x14000369 RID: 873
		// (add) Token: 0x0600432C RID: 17196 RVA: 0x0012058B File Offset: 0x0011E78B
		// (remove) Token: 0x0600432D RID: 17197 RVA: 0x00120599 File Offset: 0x0011E799
		public event ToolStripItemRenderEventHandler RenderDropDownButtonBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderDropDownButtonBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderDropDownButtonBackground, value);
			}
		}

		/// <summary>Occurs when the background for an overflow button is rendered.</summary>
		// Token: 0x1400036A RID: 874
		// (add) Token: 0x0600432E RID: 17198 RVA: 0x001205A7 File Offset: 0x0011E7A7
		// (remove) Token: 0x0600432F RID: 17199 RVA: 0x001205B5 File Offset: 0x0011E7B5
		public event ToolStripItemRenderEventHandler RenderOverflowButtonBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderOverflowButtonBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderOverflowButtonBackground, value);
			}
		}

		/// <summary>Occurs when the move handle for a <see cref="T:System.Windows.Forms.ToolStrip" /> is rendered.</summary>
		// Token: 0x1400036B RID: 875
		// (add) Token: 0x06004330 RID: 17200 RVA: 0x001205C3 File Offset: 0x0011E7C3
		// (remove) Token: 0x06004331 RID: 17201 RVA: 0x001205D1 File Offset: 0x0011E7D1
		public event ToolStripGripRenderEventHandler RenderGrip
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderGrip, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderGrip, value);
			}
		}

		/// <summary>Occurs when the background for a <see cref="T:System.Windows.Forms.ToolStripItem" /> is rendered.</summary>
		// Token: 0x1400036C RID: 876
		// (add) Token: 0x06004332 RID: 17202 RVA: 0x001205DF File Offset: 0x0011E7DF
		// (remove) Token: 0x06004333 RID: 17203 RVA: 0x001205ED File Offset: 0x0011E7ED
		public event ToolStripItemRenderEventHandler RenderItemBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderItemBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderItemBackground, value);
			}
		}

		/// <summary>Occurs when the image for a <see cref="T:System.Windows.Forms.ToolStripItem" /> is rendered.</summary>
		// Token: 0x1400036D RID: 877
		// (add) Token: 0x06004334 RID: 17204 RVA: 0x001205FB File Offset: 0x0011E7FB
		// (remove) Token: 0x06004335 RID: 17205 RVA: 0x00120609 File Offset: 0x0011E809
		public event ToolStripItemImageRenderEventHandler RenderItemImage
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderItemImage, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderItemImage, value);
			}
		}

		/// <summary>Occurs when the image for a selected <see cref="T:System.Windows.Forms.ToolStripItem" /> is rendered.</summary>
		// Token: 0x1400036E RID: 878
		// (add) Token: 0x06004336 RID: 17206 RVA: 0x00120617 File Offset: 0x0011E817
		// (remove) Token: 0x06004337 RID: 17207 RVA: 0x00120625 File Offset: 0x0011E825
		public event ToolStripItemImageRenderEventHandler RenderItemCheck
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderItemCheck, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderItemCheck, value);
			}
		}

		/// <summary>Occurs when the text for a <see cref="T:System.Windows.Forms.ToolStripItem" /> is rendered.</summary>
		// Token: 0x1400036F RID: 879
		// (add) Token: 0x06004338 RID: 17208 RVA: 0x00120633 File Offset: 0x0011E833
		// (remove) Token: 0x06004339 RID: 17209 RVA: 0x00120641 File Offset: 0x0011E841
		public event ToolStripItemTextRenderEventHandler RenderItemText
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderItemText, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderItemText, value);
			}
		}

		/// <summary>Draws the margin between an image and its container. </summary>
		// Token: 0x14000370 RID: 880
		// (add) Token: 0x0600433A RID: 17210 RVA: 0x0012064F File Offset: 0x0011E84F
		// (remove) Token: 0x0600433B RID: 17211 RVA: 0x0012065D File Offset: 0x0011E85D
		public event ToolStripRenderEventHandler RenderImageMargin
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderImageMargin, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderImageMargin, value);
			}
		}

		/// <summary>Occurs when the background for a <see cref="T:System.Windows.Forms.ToolStripLabel" /> is rendered.</summary>
		// Token: 0x14000371 RID: 881
		// (add) Token: 0x0600433C RID: 17212 RVA: 0x0012066B File Offset: 0x0011E86B
		// (remove) Token: 0x0600433D RID: 17213 RVA: 0x00120679 File Offset: 0x0011E879
		public event ToolStripItemRenderEventHandler RenderLabelBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderLabelBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderLabelBackground, value);
			}
		}

		/// <summary>Occurs when the background for a <see cref="T:System.Windows.Forms.ToolStripMenuItem" /> is rendered.</summary>
		// Token: 0x14000372 RID: 882
		// (add) Token: 0x0600433E RID: 17214 RVA: 0x00120687 File Offset: 0x0011E887
		// (remove) Token: 0x0600433F RID: 17215 RVA: 0x00120695 File Offset: 0x0011E895
		public event ToolStripItemRenderEventHandler RenderMenuItemBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderMenuItemBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderMenuItemBackground, value);
			}
		}

		/// <summary>Draws the background of a <see cref="T:System.Windows.Forms.ToolStripStatusLabel" />.</summary>
		// Token: 0x14000373 RID: 883
		// (add) Token: 0x06004340 RID: 17216 RVA: 0x001206A3 File Offset: 0x0011E8A3
		// (remove) Token: 0x06004341 RID: 17217 RVA: 0x001206B1 File Offset: 0x0011E8B1
		public event ToolStripItemRenderEventHandler RenderToolStripStatusLabelBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderToolStripStatusLabelBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderToolStripStatusLabelBackground, value);
			}
		}

		/// <summary>Occurs when the display style changes.</summary>
		// Token: 0x14000374 RID: 884
		// (add) Token: 0x06004342 RID: 17218 RVA: 0x001206BF File Offset: 0x0011E8BF
		// (remove) Token: 0x06004343 RID: 17219 RVA: 0x001206CD File Offset: 0x0011E8CD
		public event ToolStripRenderEventHandler RenderStatusStripSizingGrip
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderStatusStripSizingGrip, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderStatusStripSizingGrip, value);
			}
		}

		/// <summary>Occurs when the background for a <see cref="T:System.Windows.Forms.ToolStripSplitButton" /> is rendered.</summary>
		// Token: 0x14000375 RID: 885
		// (add) Token: 0x06004344 RID: 17220 RVA: 0x001206DB File Offset: 0x0011E8DB
		// (remove) Token: 0x06004345 RID: 17221 RVA: 0x001206E9 File Offset: 0x0011E8E9
		public event ToolStripItemRenderEventHandler RenderSplitButtonBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderSplitButtonBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderSplitButtonBackground, value);
			}
		}

		/// <summary>Occurs when a <see cref="T:System.Windows.Forms.ToolStripSeparator" /> is rendered.</summary>
		// Token: 0x14000376 RID: 886
		// (add) Token: 0x06004346 RID: 17222 RVA: 0x001206F7 File Offset: 0x0011E8F7
		// (remove) Token: 0x06004347 RID: 17223 RVA: 0x00120705 File Offset: 0x0011E905
		public event ToolStripSeparatorRenderEventHandler RenderSeparator
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderSeparator, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderSeparator, value);
			}
		}

		// Token: 0x06004348 RID: 17224 RVA: 0x00120713 File Offset: 0x0011E913
		[UIPermission(SecurityAction.Demand, Window = UIPermissionWindow.AllWindows)]
		private void AddHandler(object key, Delegate value)
		{
			this.Events.AddHandler(key, value);
		}

		// Token: 0x06004349 RID: 17225 RVA: 0x00120722 File Offset: 0x0011E922
		[UIPermission(SecurityAction.Demand, Window = UIPermissionWindow.AllWindows)]
		private void RemoveHandler(object key, Delegate value)
		{
			this.Events.RemoveHandler(key, value);
		}

		/// <summary>Creates a gray-scale copy of a given image.</summary>
		/// <param name="normalImage">The image to be copied. </param>
		/// <returns>An <see cref="T:System.Drawing.Image" /> that is a copy of the given image, but with a gray-scale color matrix.</returns>
		// Token: 0x0600434A RID: 17226 RVA: 0x00120731 File Offset: 0x0011E931
		public static Image CreateDisabledImage(Image normalImage)
		{
			return ToolStripRenderer.CreateDisabledImage(normalImage, null);
		}

		/// <summary>Draws an arrow on a <see cref="T:System.Windows.Forms.ToolStripItem" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripArrowRenderEventArgs" /> that contains data to draw the arrow.</param>
		// Token: 0x0600434B RID: 17227 RVA: 0x0012073C File Offset: 0x0011E93C
		public void DrawArrow(ToolStripArrowRenderEventArgs e)
		{
			this.OnRenderArrow(e);
			ToolStripArrowRenderEventHandler toolStripArrowRenderEventHandler = this.Events[ToolStripRenderer.EventRenderArrow] as ToolStripArrowRenderEventHandler;
			if (toolStripArrowRenderEventHandler != null)
			{
				toolStripArrowRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws the background for a <see cref="T:System.Windows.Forms.ToolStrip" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripRenderEventArgs" /> that contains the data to draw the background for the <see cref="T:System.Windows.Forms.ToolStrip" />.</param>
		// Token: 0x0600434C RID: 17228 RVA: 0x00120774 File Offset: 0x0011E974
		public void DrawToolStripBackground(ToolStripRenderEventArgs e)
		{
			this.OnRenderToolStripBackground(e);
			ToolStripRenderEventHandler toolStripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderToolStripBackground] as ToolStripRenderEventHandler;
			if (toolStripRenderEventHandler != null)
			{
				toolStripRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws a move handle on a <see cref="T:System.Windows.Forms.ToolStrip" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripGripRenderEventArgs" /> that contains the data to draw the move handle.</param>
		// Token: 0x0600434D RID: 17229 RVA: 0x001207AC File Offset: 0x0011E9AC
		public void DrawGrip(ToolStripGripRenderEventArgs e)
		{
			this.OnRenderGrip(e);
			ToolStripGripRenderEventHandler toolStripGripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderGrip] as ToolStripGripRenderEventHandler;
			if (toolStripGripRenderEventHandler != null)
			{
				toolStripGripRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws the background for a <see cref="T:System.Windows.Forms.ToolStripItem" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the data to draw the background of the item.</param>
		// Token: 0x0600434E RID: 17230 RVA: 0x001207E4 File Offset: 0x0011E9E4
		public void DrawItemBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderItemBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderItemBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws the space around an image on a <see cref="T:System.Windows.Forms.ToolStrip" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripRenderEventArgs" /> that contains the data to draw the space around the image.</param>
		// Token: 0x0600434F RID: 17231 RVA: 0x0012081C File Offset: 0x0011EA1C
		public void DrawImageMargin(ToolStripRenderEventArgs e)
		{
			this.OnRenderImageMargin(e);
			ToolStripRenderEventHandler toolStripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderImageMargin] as ToolStripRenderEventHandler;
			if (toolStripRenderEventHandler != null)
			{
				toolStripRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws the background for a <see cref="T:System.Windows.Forms.ToolStripLabel" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the data to draw the background for the label.</param>
		// Token: 0x06004350 RID: 17232 RVA: 0x00120854 File Offset: 0x0011EA54
		public void DrawLabelBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderLabelBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderLabelBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws the background for a <see cref="T:System.Windows.Forms.ToolStripButton" />.</summary>
		/// <param name="e">The <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains data to draw the button's background.</param>
		// Token: 0x06004351 RID: 17233 RVA: 0x0012088C File Offset: 0x0011EA8C
		public void DrawButtonBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderButtonBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderButtonBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws the border for a <see cref="T:System.Windows.Forms.ToolStrip" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripRenderEventArgs" /> that contains the data to draw the border for the <see cref="T:System.Windows.Forms.ToolStrip" />.</param>
		// Token: 0x06004352 RID: 17234 RVA: 0x001208C4 File Offset: 0x0011EAC4
		public void DrawToolStripBorder(ToolStripRenderEventArgs e)
		{
			this.OnRenderToolStripBorder(e);
			ToolStripRenderEventHandler toolStripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderBorder] as ToolStripRenderEventHandler;
			if (toolStripRenderEventHandler != null)
			{
				toolStripRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws the background for a <see cref="T:System.Windows.Forms.ToolStripDropDownButton" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the data to draw the drop-down button's background.</param>
		// Token: 0x06004353 RID: 17235 RVA: 0x001208FC File Offset: 0x0011EAFC
		public void DrawDropDownButtonBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderDropDownButtonBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderDropDownButtonBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws the background for an overflow button.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x06004354 RID: 17236 RVA: 0x00120934 File Offset: 0x0011EB34
		public void DrawOverflowButtonBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderOverflowButtonBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderOverflowButtonBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws an image on a <see cref="T:System.Windows.Forms.ToolStripItem" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemImageRenderEventArgs" /> that contains the data to draw the image.</param>
		// Token: 0x06004355 RID: 17237 RVA: 0x0012096C File Offset: 0x0011EB6C
		public void DrawItemImage(ToolStripItemImageRenderEventArgs e)
		{
			this.OnRenderItemImage(e);
			ToolStripItemImageRenderEventHandler toolStripItemImageRenderEventHandler = this.Events[ToolStripRenderer.EventRenderItemImage] as ToolStripItemImageRenderEventHandler;
			if (toolStripItemImageRenderEventHandler != null)
			{
				toolStripItemImageRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws an image on a <see cref="T:System.Windows.Forms.ToolStripItem" /> that indicates the item is in a selected state.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemImageRenderEventArgs" /> that contains the data to draw the selected image.</param>
		// Token: 0x06004356 RID: 17238 RVA: 0x001209A4 File Offset: 0x0011EBA4
		public void DrawItemCheck(ToolStripItemImageRenderEventArgs e)
		{
			this.OnRenderItemCheck(e);
			ToolStripItemImageRenderEventHandler toolStripItemImageRenderEventHandler = this.Events[ToolStripRenderer.EventRenderItemCheck] as ToolStripItemImageRenderEventHandler;
			if (toolStripItemImageRenderEventHandler != null)
			{
				toolStripItemImageRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws text on a <see cref="T:System.Windows.Forms.ToolStripItem" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemTextRenderEventArgs" /> that contains the data to draw the text.</param>
		// Token: 0x06004357 RID: 17239 RVA: 0x001209DC File Offset: 0x0011EBDC
		public void DrawItemText(ToolStripItemTextRenderEventArgs e)
		{
			this.OnRenderItemText(e);
			ToolStripItemTextRenderEventHandler toolStripItemTextRenderEventHandler = this.Events[ToolStripRenderer.EventRenderItemText] as ToolStripItemTextRenderEventHandler;
			if (toolStripItemTextRenderEventHandler != null)
			{
				toolStripItemTextRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws the background for a <see cref="T:System.Windows.Forms.ToolStripMenuItem" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the data to draw the background for the menu item.</param>
		// Token: 0x06004358 RID: 17240 RVA: 0x00120A14 File Offset: 0x0011EC14
		public void DrawMenuItemBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderMenuItemBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderMenuItemBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws a <see cref="T:System.Windows.Forms.ToolStripSplitButton" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the event data. </param>
		// Token: 0x06004359 RID: 17241 RVA: 0x00120A4C File Offset: 0x0011EC4C
		public void DrawSplitButton(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderSplitButtonBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderSplitButtonBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws the background of the <see cref="T:System.Windows.Forms.ToolStripStatusLabel" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x0600435A RID: 17242 RVA: 0x00120A84 File Offset: 0x0011EC84
		public void DrawToolStripStatusLabelBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderToolStripStatusLabelBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderToolStripStatusLabelBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws a sizing grip.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x0600435B RID: 17243 RVA: 0x00120ABC File Offset: 0x0011ECBC
		public void DrawStatusStripSizingGrip(ToolStripRenderEventArgs e)
		{
			this.OnRenderStatusStripSizingGrip(e);
			ToolStripRenderEventHandler toolStripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderStatusStripSizingGrip] as ToolStripRenderEventHandler;
			if (toolStripRenderEventHandler != null)
			{
				toolStripRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws a <see cref="T:System.Windows.Forms.ToolStripSeparator" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripSeparatorRenderEventArgs" /> that contains the data to draw the <see cref="T:System.Windows.Forms.ToolStripSeparator" />.</param>
		// Token: 0x0600435C RID: 17244 RVA: 0x00120AF4 File Offset: 0x0011ECF4
		public void DrawSeparator(ToolStripSeparatorRenderEventArgs e)
		{
			this.OnRenderSeparator(e);
			ToolStripSeparatorRenderEventHandler toolStripSeparatorRenderEventHandler = this.Events[ToolStripRenderer.EventRenderSeparator] as ToolStripSeparatorRenderEventHandler;
			if (toolStripSeparatorRenderEventHandler != null)
			{
				toolStripSeparatorRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws the background of the <see cref="T:System.Windows.Forms.ToolStripPanel" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripPanelRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x0600435D RID: 17245 RVA: 0x00120B2C File Offset: 0x0011ED2C
		public void DrawToolStripPanelBackground(ToolStripPanelRenderEventArgs e)
		{
			this.OnRenderToolStripPanelBackground(e);
			ToolStripPanelRenderEventHandler toolStripPanelRenderEventHandler = this.Events[ToolStripRenderer.EventRenderToolStripPanelBackground] as ToolStripPanelRenderEventHandler;
			if (toolStripPanelRenderEventHandler != null)
			{
				toolStripPanelRenderEventHandler(this, e);
			}
		}

		/// <summary>Draws the background of the <see cref="T:System.Windows.Forms.ToolStripContentPanel" />.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripContentPanelRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x0600435E RID: 17246 RVA: 0x00120B64 File Offset: 0x0011ED64
		public void DrawToolStripContentPanelBackground(ToolStripContentPanelRenderEventArgs e)
		{
			this.OnRenderToolStripContentPanelBackground(e);
			ToolStripContentPanelRenderEventHandler toolStripContentPanelRenderEventHandler = this.Events[ToolStripRenderer.EventRenderToolStripContentPanelBackground] as ToolStripContentPanelRenderEventHandler;
			if (toolStripContentPanelRenderEventHandler != null)
			{
				toolStripContentPanelRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600435F RID: 17247 RVA: 0x0000DE5C File Offset: 0x0000C05C
		internal virtual Region GetTransparentRegion(ToolStrip toolStrip)
		{
			return null;
		}

		/// <summary>When overridden in a derived class, provides for custom initialization of the given <see cref="T:System.Windows.Forms.ToolStrip" />. </summary>
		/// <param name="toolStrip">The <see cref="T:System.Windows.Forms.ToolStrip" /> to be initialized.</param>
		// Token: 0x06004360 RID: 17248 RVA: 0x0000701A File Offset: 0x0000521A
		protected internal virtual void Initialize(ToolStrip toolStrip)
		{
		}

		/// <summary>Initializes the specified <see cref="T:System.Windows.Forms.ToolStripPanel" />.</summary>
		/// <param name="toolStripPanel">The <see cref="T:System.Windows.Forms.ToolStripPanel" />.</param>
		// Token: 0x06004361 RID: 17249 RVA: 0x0000701A File Offset: 0x0000521A
		protected internal virtual void InitializePanel(ToolStripPanel toolStripPanel)
		{
		}

		/// <summary>Initializes the specified <see cref="T:System.Windows.Forms.ToolStripContentPanel" />.</summary>
		/// <param name="contentPanel">The <see cref="T:System.Windows.Forms.ToolStripContentPanel" />.</param>
		// Token: 0x06004362 RID: 17250 RVA: 0x0000701A File Offset: 0x0000521A
		protected internal virtual void InitializeContentPanel(ToolStripContentPanel contentPanel)
		{
		}

		/// <summary>When overridden in a derived class, provides for custom initialization of the given <see cref="T:System.Windows.Forms.ToolStripItem" />. </summary>
		/// <param name="item">The <see cref="T:System.Windows.Forms.ToolStripItem" /> to be initialized.</param>
		// Token: 0x06004363 RID: 17251 RVA: 0x0000701A File Offset: 0x0000521A
		protected internal virtual void InitializeItem(ToolStripItem item)
		{
		}

		/// <summary>Applies the F:System.Windows.Forms.ToolStripRenderer.Offset2X and F:System.Windows.Forms.ToolStripRenderer.Offset2Y specified to scaling the arrow icon, if scaling is required per the DPI settings of the computer.</summary>
		// Token: 0x06004364 RID: 17252 RVA: 0x00120B9C File Offset: 0x0011ED9C
		protected static void ScaleArrowOffsetsIfNeeded()
		{
			if (ToolStripRenderer.isScalingInitialized)
			{
				return;
			}
			if (DpiHelper.IsScalingRequired)
			{
				ToolStripRenderer.Offset2X = DpiHelper.LogicalToDeviceUnitsX(ToolStripRenderer.OFFSET_2PIXELS);
				ToolStripRenderer.Offset2Y = DpiHelper.LogicalToDeviceUnitsY(ToolStripRenderer.OFFSET_2PIXELS);
				ToolStripRenderer.offset4X = DpiHelper.LogicalToDeviceUnitsX(ToolStripRenderer.OFFSET_4PIXELS);
				ToolStripRenderer.offset4Y = DpiHelper.LogicalToDeviceUnitsY(ToolStripRenderer.OFFSET_4PIXELS);
			}
			ToolStripRenderer.isScalingInitialized = true;
		}

		// Token: 0x06004365 RID: 17253 RVA: 0x00120BFC File Offset: 0x0011EDFC
		protected static void ScaleArrowOffsetsIfNeeded(int dpi)
		{
			ToolStripRenderer.Offset2X = DpiHelper.LogicalToDeviceUnits(ToolStripRenderer.OFFSET_2PIXELS, dpi);
			ToolStripRenderer.Offset2Y = DpiHelper.LogicalToDeviceUnits(ToolStripRenderer.OFFSET_2PIXELS, dpi);
			ToolStripRenderer.offset4X = DpiHelper.LogicalToDeviceUnits(ToolStripRenderer.OFFSET_4PIXELS, dpi);
			ToolStripRenderer.offset4Y = DpiHelper.LogicalToDeviceUnits(ToolStripRenderer.OFFSET_4PIXELS, dpi);
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderArrow" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripArrowRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x06004366 RID: 17254 RVA: 0x00120C4C File Offset: 0x0011EE4C
		protected virtual void OnRenderArrow(ToolStripArrowRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderArrow(e);
				return;
			}
			Graphics graphics = e.Graphics;
			Rectangle arrowRectangle = e.ArrowRectangle;
			using (Brush brush = new SolidBrush(e.ArrowColor))
			{
				Point point = new Point(arrowRectangle.Left + arrowRectangle.Width / 2, arrowRectangle.Top + arrowRectangle.Height / 2);
				ToolStripItem item = e.Item;
				if (((item != null) ? new int?(item.DeviceDpi) : null) != this.previousDeviceDpi && DpiHelper.EnableToolStripPerMonitorV2HighDpiImprovements)
				{
					this.previousDeviceDpi = e.Item.DeviceDpi;
					ToolStripRenderer.ScaleArrowOffsetsIfNeeded(e.Item.DeviceDpi);
				}
				else
				{
					ToolStripRenderer.ScaleArrowOffsetsIfNeeded();
				}
				int num = DpiHelper.EnableToolStripHighDpiImprovements ? (ToolStripRenderer.offset4X - ToolStripRenderer.Offset2X) : ToolStripRenderer.Offset2X;
				ArrowDirection direction = e.Direction;
				Point[] points;
				if (direction <= ArrowDirection.Up)
				{
					if (direction == ArrowDirection.Left)
					{
						points = new Point[]
						{
							new Point(point.X + ToolStripRenderer.Offset2X, point.Y - ToolStripRenderer.offset4Y),
							new Point(point.X + ToolStripRenderer.Offset2X, point.Y + ToolStripRenderer.offset4Y),
							new Point(point.X - num, point.Y)
						};
						goto IL_2E8;
					}
					if (direction == ArrowDirection.Up)
					{
						points = new Point[]
						{
							new Point(point.X - ToolStripRenderer.Offset2X, point.Y + 1),
							new Point(point.X + ToolStripRenderer.Offset2X + 1, point.Y + 1),
							new Point(point.X, point.Y - ToolStripRenderer.Offset2Y)
						};
						goto IL_2E8;
					}
				}
				else
				{
					if (direction == ArrowDirection.Right)
					{
						points = new Point[]
						{
							new Point(point.X - ToolStripRenderer.Offset2X, point.Y - ToolStripRenderer.offset4Y),
							new Point(point.X - ToolStripRenderer.Offset2X, point.Y + ToolStripRenderer.offset4Y),
							new Point(point.X + num, point.Y)
						};
						goto IL_2E8;
					}
					if (direction != ArrowDirection.Down)
					{
					}
				}
				points = new Point[]
				{
					new Point(point.X - ToolStripRenderer.Offset2X, point.Y - 1),
					new Point(point.X + ToolStripRenderer.Offset2X + 1, point.Y - 1),
					new Point(point.X, point.Y + ToolStripRenderer.Offset2Y)
				};
				IL_2E8:
				graphics.FillPolygon(brush, points);
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderToolStripBackground" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripRenderEventArgs" /> that contains the event data. </param>
		// Token: 0x06004367 RID: 17255 RVA: 0x00120F74 File Offset: 0x0011F174
		protected virtual void OnRenderToolStripBackground(ToolStripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripBackground(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderToolStripBorder" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x06004368 RID: 17256 RVA: 0x00120F8B File Offset: 0x0011F18B
		protected virtual void OnRenderToolStripBorder(ToolStripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripBorder(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderGrip" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripGripRenderEventArgs" /> that contains the event data. </param>
		// Token: 0x06004369 RID: 17257 RVA: 0x00120FA2 File Offset: 0x0011F1A2
		protected virtual void OnRenderGrip(ToolStripGripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderGrip(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="M:System.Windows.Forms.ToolStripSystemRenderer.OnRenderItemBackground(System.Windows.Forms.ToolStripItemRenderEventArgs)" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the event data. </param>
		// Token: 0x0600436A RID: 17258 RVA: 0x00120FB9 File Offset: 0x0011F1B9
		protected virtual void OnRenderItemBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderItemBackground(e);
				return;
			}
		}

		/// <summary>Draws the item background.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripRenderEventArgs" /> that contains the event data. </param>
		// Token: 0x0600436B RID: 17259 RVA: 0x00120FD0 File Offset: 0x0011F1D0
		protected virtual void OnRenderImageMargin(ToolStripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderImageMargin(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderButtonBackground" /> event.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripRenderEventArgs" /> that contains the event data. </param>
		// Token: 0x0600436C RID: 17260 RVA: 0x00120FE7 File Offset: 0x0011F1E7
		protected virtual void OnRenderButtonBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderButtonBackground(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderDropDownButtonBackground" /> event.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the event data. </param>
		// Token: 0x0600436D RID: 17261 RVA: 0x00120FFE File Offset: 0x0011F1FE
		protected virtual void OnRenderDropDownButtonBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderDropDownButtonBackground(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderOverflowButtonBackground" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the event data. </param>
		// Token: 0x0600436E RID: 17262 RVA: 0x00121015 File Offset: 0x0011F215
		protected virtual void OnRenderOverflowButtonBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderOverflowButtonBackground(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderItemImage" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemImageRenderEventArgs" /> that contains the event data. </param>
		// Token: 0x0600436F RID: 17263 RVA: 0x0012102C File Offset: 0x0011F22C
		protected virtual void OnRenderItemImage(ToolStripItemImageRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderItemImage(e);
				return;
			}
			Rectangle imageRectangle = e.ImageRectangle;
			Image image = e.Image;
			if (imageRectangle != Rectangle.Empty && image != null)
			{
				bool flag = false;
				if (e.ShiftOnPress && e.Item.Pressed)
				{
					imageRectangle.X++;
				}
				if (!e.Item.Enabled)
				{
					image = ToolStripRenderer.CreateDisabledImage(image, e.ImageAttributes);
					flag = true;
				}
				if (e.Item.ImageScaling == ToolStripItemImageScaling.None)
				{
					e.Graphics.DrawImage(image, imageRectangle, new Rectangle(Point.Empty, imageRectangle.Size), GraphicsUnit.Pixel);
				}
				else
				{
					e.Graphics.DrawImage(image, imageRectangle);
				}
				if (flag)
				{
					image.Dispose();
				}
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderItemCheck" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemImageRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x06004370 RID: 17264 RVA: 0x001210F8 File Offset: 0x0011F2F8
		protected virtual void OnRenderItemCheck(ToolStripItemImageRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderItemCheck(e);
				return;
			}
			Rectangle imageRectangle = e.ImageRectangle;
			Image image = e.Image;
			if (imageRectangle != Rectangle.Empty && image != null)
			{
				if (!e.Item.Enabled)
				{
					image = ToolStripRenderer.CreateDisabledImage(image, e.ImageAttributes);
				}
				e.Graphics.DrawImage(image, imageRectangle, 0, 0, imageRectangle.Width, imageRectangle.Height, GraphicsUnit.Pixel, e.ImageAttributes);
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderItemText" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemTextRenderEventArgs" /> that contains the event data. </param>
		// Token: 0x06004371 RID: 17265 RVA: 0x00121178 File Offset: 0x0011F378
		protected virtual void OnRenderItemText(ToolStripItemTextRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderItemText(e);
				return;
			}
			ToolStripItem item = e.Item;
			Graphics graphics = e.Graphics;
			Color color = e.TextColor;
			Font textFont = e.TextFont;
			string text = e.Text;
			Rectangle textRectangle = e.TextRectangle;
			TextFormatFlags textFormat = e.TextFormat;
			color = (item.Enabled ? color : SystemColors.GrayText);
			if (e.TextDirection != ToolStripTextDirection.Horizontal && textRectangle.Width > 0 && textRectangle.Height > 0)
			{
				Size size = LayoutUtils.FlipSize(textRectangle.Size);
				using (Bitmap bitmap = new Bitmap(size.Width, size.Height, PixelFormat.Format32bppPArgb))
				{
					using (Graphics graphics2 = Graphics.FromImage(bitmap))
					{
						graphics2.TextRenderingHint = TextRenderingHint.AntiAlias;
						TextRenderer.DrawText(graphics2, text, textFont, new Rectangle(Point.Empty, size), color, textFormat);
						bitmap.RotateFlip((e.TextDirection == ToolStripTextDirection.Vertical90) ? RotateFlipType.Rotate90FlipNone : RotateFlipType.Rotate270FlipNone);
						graphics.DrawImage(bitmap, textRectangle);
						return;
					}
				}
			}
			TextRenderer.DrawText(graphics, text, textFont, textRectangle, color, textFormat);
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderLabelBackground" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x06004372 RID: 17266 RVA: 0x001212BC File Offset: 0x0011F4BC
		protected virtual void OnRenderLabelBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderLabelBackground(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderMenuItemBackground" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x06004373 RID: 17267 RVA: 0x001212D3 File Offset: 0x0011F4D3
		protected virtual void OnRenderMenuItemBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderMenuItemBackground(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderSeparator" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripSeparatorRenderEventArgs" /> that contains the event data. </param>
		// Token: 0x06004374 RID: 17268 RVA: 0x001212EA File Offset: 0x0011F4EA
		protected virtual void OnRenderSeparator(ToolStripSeparatorRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderSeparator(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderToolStripPanelBackground" /> event.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripPanelRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x06004375 RID: 17269 RVA: 0x00121301 File Offset: 0x0011F501
		protected virtual void OnRenderToolStripPanelBackground(ToolStripPanelRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripPanelBackground(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderToolStripContentPanelBackground" /> event.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripContentPanelRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x06004376 RID: 17270 RVA: 0x00121318 File Offset: 0x0011F518
		protected virtual void OnRenderToolStripContentPanelBackground(ToolStripContentPanelRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripContentPanelBackground(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderToolStripStatusLabelBackground" /> event.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x06004377 RID: 17271 RVA: 0x0012132F File Offset: 0x0011F52F
		protected virtual void OnRenderToolStripStatusLabelBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripStatusLabelBackground(e);
				return;
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripRenderer.RenderStatusStripSizingGrip" /> event.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x06004378 RID: 17272 RVA: 0x00121348 File Offset: 0x0011F548
		protected virtual void OnRenderStatusStripSizingGrip(ToolStripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderStatusStripSizingGrip(e);
				return;
			}
			Graphics graphics = e.Graphics;
			StatusStrip statusStrip = e.ToolStrip as StatusStrip;
			if (statusStrip != null)
			{
				Rectangle sizeGripBounds = statusStrip.SizeGripBounds;
				if (!LayoutUtils.IsZeroWidthOrHeight(sizeGripBounds))
				{
					Rectangle[] array = new Rectangle[ToolStripRenderer.baseSizeGripRectangles.Length];
					Rectangle[] array2 = new Rectangle[ToolStripRenderer.baseSizeGripRectangles.Length];
					for (int i = 0; i < ToolStripRenderer.baseSizeGripRectangles.Length; i++)
					{
						Rectangle rectangle = ToolStripRenderer.baseSizeGripRectangles[i];
						if (statusStrip.RightToLeft == RightToLeft.Yes)
						{
							rectangle.X = sizeGripBounds.Width - rectangle.X - rectangle.Width;
						}
						rectangle.Offset(sizeGripBounds.X, sizeGripBounds.Bottom - 12);
						array[i] = rectangle;
						if (statusStrip.RightToLeft == RightToLeft.Yes)
						{
							rectangle.Offset(1, -1);
						}
						else
						{
							rectangle.Offset(-1, -1);
						}
						array2[i] = rectangle;
					}
					graphics.FillRectangles(SystemBrushes.ButtonHighlight, array);
					graphics.FillRectangles(SystemBrushes.ButtonShadow, array2);
				}
			}
		}

		/// <summary>Raises the <see cref="M:System.Windows.Forms.ToolStripRenderer.OnRenderSplitButtonBackground(System.Windows.Forms.ToolStripItemRenderEventArgs)" /> event. </summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemRenderEventArgs" /> that contains the event data.</param>
		// Token: 0x06004379 RID: 17273 RVA: 0x00121464 File Offset: 0x0011F664
		protected virtual void OnRenderSplitButtonBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderSplitButtonBackground(e);
				return;
			}
		}

		// Token: 0x0600437A RID: 17274 RVA: 0x0012147B File Offset: 0x0011F67B
		internal bool ShouldPaintBackground(Control control)
		{
			return control.RawBackColor == Color.Empty && control.BackgroundImage == null;
		}

		// Token: 0x0600437B RID: 17275 RVA: 0x0012149C File Offset: 0x0011F69C
		private static Image CreateDisabledImage(Image normalImage, ImageAttributes imgAttrib)
		{
			if (imgAttrib == null)
			{
				imgAttrib = new ImageAttributes();
			}
			imgAttrib.ClearColorKey();
			imgAttrib.SetColorMatrix(ToolStripRenderer.DisabledImageColorMatrix);
			Size size = normalImage.Size;
			Bitmap bitmap = new Bitmap(size.Width, size.Height);
			using (Graphics graphics = Graphics.FromImage(bitmap))
			{
				graphics.DrawImage(normalImage, new Rectangle(0, 0, size.Width, size.Height), 0, 0, size.Width, size.Height, GraphicsUnit.Pixel, imgAttrib);
			}
			return bitmap;
		}

		// Token: 0x04002577 RID: 9591
		private static readonly object EventRenderSplitButtonBackground = new object();

		// Token: 0x04002578 RID: 9592
		private static readonly object EventRenderItemBackground = new object();

		// Token: 0x04002579 RID: 9593
		private static readonly object EventRenderItemImage = new object();

		// Token: 0x0400257A RID: 9594
		private static readonly object EventRenderItemText = new object();

		// Token: 0x0400257B RID: 9595
		private static readonly object EventRenderToolStripBackground = new object();

		// Token: 0x0400257C RID: 9596
		private static readonly object EventRenderGrip = new object();

		// Token: 0x0400257D RID: 9597
		private static readonly object EventRenderButtonBackground = new object();

		// Token: 0x0400257E RID: 9598
		private static readonly object EventRenderLabelBackground = new object();

		// Token: 0x0400257F RID: 9599
		private static readonly object EventRenderMenuItemBackground = new object();

		// Token: 0x04002580 RID: 9600
		private static readonly object EventRenderDropDownButtonBackground = new object();

		// Token: 0x04002581 RID: 9601
		private static readonly object EventRenderOverflowButtonBackground = new object();

		// Token: 0x04002582 RID: 9602
		private static readonly object EventRenderImageMargin = new object();

		// Token: 0x04002583 RID: 9603
		private static readonly object EventRenderBorder = new object();

		// Token: 0x04002584 RID: 9604
		private static readonly object EventRenderArrow = new object();

		// Token: 0x04002585 RID: 9605
		private static readonly object EventRenderStatusStripPanelBackground = new object();

		// Token: 0x04002586 RID: 9606
		private static readonly object EventRenderToolStripStatusLabelBackground = new object();

		// Token: 0x04002587 RID: 9607
		private static readonly object EventRenderSeparator = new object();

		// Token: 0x04002588 RID: 9608
		private static readonly object EventRenderItemCheck = new object();

		// Token: 0x04002589 RID: 9609
		private static readonly object EventRenderToolStripPanelBackground = new object();

		// Token: 0x0400258A RID: 9610
		private static readonly object EventRenderToolStripContentPanelBackground = new object();

		// Token: 0x0400258B RID: 9611
		private static readonly object EventRenderStatusStripSizingGrip = new object();

		// Token: 0x0400258C RID: 9612
		private static ColorMatrix disabledImageColorMatrix;

		// Token: 0x0400258D RID: 9613
		private EventHandlerList events;

		// Token: 0x0400258E RID: 9614
		private bool isAutoGenerated;

		// Token: 0x0400258F RID: 9615
		private static bool isScalingInitialized = false;

		// Token: 0x04002590 RID: 9616
		internal int previousDeviceDpi = DpiHelper.DeviceDpi;

		// Token: 0x04002591 RID: 9617
		private static int OFFSET_2PIXELS = 2;

		// Token: 0x04002592 RID: 9618
		private static int OFFSET_4PIXELS = 4;

		/// <summary>Gets or sets the offset multiplier for twice the offset along the x-axis.</summary>
		// Token: 0x04002593 RID: 9619
		protected static int Offset2X = ToolStripRenderer.OFFSET_2PIXELS;

		/// <summary>Gets or sets the offset multiplier for twice the offset along the y axis.</summary>
		// Token: 0x04002594 RID: 9620
		protected static int Offset2Y = ToolStripRenderer.OFFSET_2PIXELS;

		// Token: 0x04002595 RID: 9621
		private static int offset4X = ToolStripRenderer.OFFSET_4PIXELS;

		// Token: 0x04002596 RID: 9622
		private static int offset4Y = ToolStripRenderer.OFFSET_4PIXELS;

		// Token: 0x04002597 RID: 9623
		private static Rectangle[] baseSizeGripRectangles = new Rectangle[]
		{
			new Rectangle(8, 0, 2, 2),
			new Rectangle(8, 4, 2, 2),
			new Rectangle(8, 8, 2, 2),
			new Rectangle(4, 4, 2, 2),
			new Rectangle(4, 8, 2, 2),
			new Rectangle(0, 8, 2, 2)
		};
	}
}
