using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Security.Permissions;
using System.Windows.Forms.Layout;

namespace System.Windows.Forms
{
	/// <summary>Provides basic functionality for controls that display a <see cref="T:System.Windows.Forms.ToolStripDropDown" /> when a <see cref="T:System.Windows.Forms.ToolStripDropDownButton" />, <see cref="T:System.Windows.Forms.ToolStripMenuItem" />, or <see cref="T:System.Windows.Forms.ToolStripSplitButton" /> control is clicked.</summary>
	// Token: 0x020003B0 RID: 944
	[Designer("System.Windows.Forms.Design.ToolStripMenuItemDesigner, System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
	[DefaultProperty("DropDownItems")]
	public abstract class ToolStripDropDownItem : ToolStripItem
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> class. </summary>
		// Token: 0x06003E06 RID: 15878 RVA: 0x0010E0EF File Offset: 0x0010C2EF
		protected ToolStripDropDownItem()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> class with the specified display text, image, and action to take when the drop-down control is clicked.</summary>
		/// <param name="text">The display text of the drop-down control.</param>
		/// <param name="image">The <see cref="T:System.Drawing.Image" /> to be displayed on the control.</param>
		/// <param name="onClick">The action to take when the drop-down control is clicked.</param>
		// Token: 0x06003E07 RID: 15879 RVA: 0x0010E0FE File Offset: 0x0010C2FE
		protected ToolStripDropDownItem(string text, Image image, EventHandler onClick) : base(text, image, onClick)
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> class with the specified display text, image, action to take when the drop-down control is clicked, and control name.</summary>
		/// <param name="text">The display text of the drop-down control.</param>
		/// <param name="image">The <see cref="T:System.Drawing.Image" /> to be displayed on the control.</param>
		/// <param name="onClick">The action to take when the drop-down control is clicked.</param>
		/// <param name="name">The name of the control.</param>
		// Token: 0x06003E08 RID: 15880 RVA: 0x0010E110 File Offset: 0x0010C310
		protected ToolStripDropDownItem(string text, Image image, EventHandler onClick, string name) : base(text, image, onClick, name)
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> class with the specified display text, image, and <see cref="T:System.Windows.Forms.ToolStripItem" /> collection that the drop-down control contains.</summary>
		/// <param name="text">The display text of the drop-down control.</param>
		/// <param name="image">The <see cref="T:System.Drawing.Image" /> to be displayed on the control.</param>
		/// <param name="dropDownItems">A <see cref="T:System.Windows.Forms.ToolStripItem" /> collection that the drop-down control contains.</param>
		// Token: 0x06003E09 RID: 15881 RVA: 0x0010E124 File Offset: 0x0010C324
		protected ToolStripDropDownItem(string text, Image image, params ToolStripItem[] dropDownItems) : this(text, image, null)
		{
			if (dropDownItems != null)
			{
				this.DropDownItems.AddRange(dropDownItems);
			}
		}

		/// <summary>Gets or sets the <see cref="T:System.Windows.Forms.ToolStripDropDown" /> that will be displayed when this <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> is clicked.</summary>
		/// <returns>A <see cref="T:System.Windows.Forms.ToolStripDropDown" /> that is associated with the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" />.</returns>
		// Token: 0x17000F7B RID: 3963
		// (get) Token: 0x06003E0A RID: 15882 RVA: 0x0010E140 File Offset: 0x0010C340
		// (set) Token: 0x06003E0B RID: 15883 RVA: 0x0010E19C File Offset: 0x0010C39C
		[TypeConverter(typeof(ReferenceConverter))]
		[SRCategory("CatData")]
		[SRDescription("ToolStripDropDownDescr")]
		public ToolStripDropDown DropDown
		{
			get
			{
				if (this.dropDown == null)
				{
					this.DropDown = this.CreateDefaultDropDown();
					if (!(this is ToolStripOverflowButton))
					{
						this.dropDown.SetAutoGeneratedInternal(true);
					}
					if (base.ParentInternal != null)
					{
						this.dropDown.ShowItemToolTips = base.ParentInternal.ShowItemToolTips;
					}
				}
				return this.dropDown;
			}
			set
			{
				if (this.dropDown != value)
				{
					if (this.dropDown != null)
					{
						this.dropDown.Opened -= this.DropDown_Opened;
						this.dropDown.Closed -= this.DropDown_Closed;
						this.dropDown.ItemClicked -= this.DropDown_ItemClicked;
						this.dropDown.UnassignDropDownItem();
					}
					this.dropDown = value;
					if (this.dropDown != null)
					{
						this.dropDown.Opened += this.DropDown_Opened;
						this.dropDown.Closed += this.DropDown_Closed;
						this.dropDown.ItemClicked += this.DropDown_ItemClicked;
						this.dropDown.AssignToDropDownItem();
					}
				}
			}
		}

		// Token: 0x17000F7C RID: 3964
		// (get) Token: 0x06003E0C RID: 15884 RVA: 0x0010E26C File Offset: 0x0010C46C
		internal virtual Rectangle DropDownButtonArea
		{
			get
			{
				return this.Bounds;
			}
		}

		/// <summary>Gets or sets a value indicating the direction in which the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> emerges from its parent container.</summary>
		/// <returns>One of the <see cref="T:System.Windows.Forms.ToolStripDropDownDirection" /> values.</returns>
		/// <exception cref="T:System.ComponentModel.InvalidEnumArgumentException">The property is set to a value that is not one of the <see cref="T:System.Windows.Forms.ToolStripDropDownDirection" /> values.</exception>
		// Token: 0x17000F7D RID: 3965
		// (get) Token: 0x06003E0D RID: 15885 RVA: 0x0010E274 File Offset: 0x0010C474
		// (set) Token: 0x06003E0E RID: 15886 RVA: 0x0010E354 File Offset: 0x0010C554
		[Browsable(false)]
		[SRDescription("ToolStripDropDownItemDropDownDirectionDescr")]
		[SRCategory("CatBehavior")]
		public ToolStripDropDownDirection DropDownDirection
		{
			get
			{
				if (this.toolStripDropDownDirection == ToolStripDropDownDirection.Default)
				{
					ToolStrip parentInternal = base.ParentInternal;
					if (parentInternal != null)
					{
						ToolStripDropDownDirection toolStripDropDownDirection = parentInternal.DefaultDropDownDirection;
						if (this.OppositeDropDownAlign || (this.RightToLeft != parentInternal.RightToLeft && this.RightToLeft != RightToLeft.Inherit))
						{
							toolStripDropDownDirection = this.RTLTranslateDropDownDirection(toolStripDropDownDirection, this.RightToLeft);
						}
						if (base.IsOnDropDown)
						{
							Rectangle dropDownBounds = this.GetDropDownBounds(toolStripDropDownDirection);
							Rectangle b = new Rectangle(base.TranslatePoint(Point.Empty, ToolStripPointType.ToolStripItemCoords, ToolStripPointType.ScreenCoords), this.Size);
							Rectangle rectangle = Rectangle.Intersect(dropDownBounds, b);
							if (rectangle.Width >= 2)
							{
								RightToLeft rightToLeft = (this.RightToLeft == RightToLeft.Yes) ? RightToLeft.No : RightToLeft.Yes;
								ToolStripDropDownDirection toolStripDropDownDirection2 = this.RTLTranslateDropDownDirection(toolStripDropDownDirection, rightToLeft);
								int width = Rectangle.Intersect(this.GetDropDownBounds(toolStripDropDownDirection2), b).Width;
								if (width < rectangle.Width)
								{
									toolStripDropDownDirection = toolStripDropDownDirection2;
								}
							}
						}
						return toolStripDropDownDirection;
					}
				}
				return this.toolStripDropDownDirection;
			}
			set
			{
				if (value > ToolStripDropDownDirection.Right && value != ToolStripDropDownDirection.Default)
				{
					throw new InvalidEnumArgumentException("value", (int)value, typeof(ToolStripDropDownDirection));
				}
				if (this.toolStripDropDownDirection != value)
				{
					this.toolStripDropDownDirection = value;
					if (this.HasDropDownItems && this.DropDown.Visible)
					{
						this.DropDown.Location = this.DropDownLocation;
					}
				}
			}
		}

		/// <summary>Occurs when the <see cref="T:System.Windows.Forms.ToolStripDropDown" /> closes. </summary>
		// Token: 0x14000324 RID: 804
		// (add) Token: 0x06003E0F RID: 15887 RVA: 0x0010E3B5 File Offset: 0x0010C5B5
		// (remove) Token: 0x06003E10 RID: 15888 RVA: 0x0010E3C8 File Offset: 0x0010C5C8
		[SRCategory("CatAction")]
		[SRDescription("ToolStripDropDownClosedDecr")]
		public event EventHandler DropDownClosed
		{
			add
			{
				base.Events.AddHandler(ToolStripDropDownItem.EventDropDownClosed, value);
			}
			remove
			{
				base.Events.RemoveHandler(ToolStripDropDownItem.EventDropDownClosed, value);
			}
		}

		/// <summary>Gets the screen coordinates, in pixels, of the upper-left corner of the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" />.</summary>
		/// <returns>A <see langword="Point" /> representing the x and y screen coordinates, in pixels.</returns>
		// Token: 0x17000F7E RID: 3966
		// (get) Token: 0x06003E11 RID: 15889 RVA: 0x0010E3DC File Offset: 0x0010C5DC
		protected internal virtual Point DropDownLocation
		{
			get
			{
				if (base.ParentInternal == null || !this.HasDropDownItems)
				{
					return Point.Empty;
				}
				ToolStripDropDownDirection dropDownDirection = this.DropDownDirection;
				return this.GetDropDownBounds(dropDownDirection).Location;
			}
		}

		/// <summary>Occurs as the <see cref="T:System.Windows.Forms.ToolStripDropDown" /> is opening.</summary>
		// Token: 0x14000325 RID: 805
		// (add) Token: 0x06003E12 RID: 15890 RVA: 0x0010E415 File Offset: 0x0010C615
		// (remove) Token: 0x06003E13 RID: 15891 RVA: 0x0010E428 File Offset: 0x0010C628
		[SRCategory("CatAction")]
		[SRDescription("ToolStripDropDownOpeningDescr")]
		public event EventHandler DropDownOpening
		{
			add
			{
				base.Events.AddHandler(ToolStripDropDownItem.EventDropDownShow, value);
			}
			remove
			{
				base.Events.RemoveHandler(ToolStripDropDownItem.EventDropDownShow, value);
			}
		}

		/// <summary>Occurs when the <see cref="T:System.Windows.Forms.ToolStripDropDown" /> has opened.</summary>
		// Token: 0x14000326 RID: 806
		// (add) Token: 0x06003E14 RID: 15892 RVA: 0x0010E43B File Offset: 0x0010C63B
		// (remove) Token: 0x06003E15 RID: 15893 RVA: 0x0010E44E File Offset: 0x0010C64E
		[SRCategory("CatAction")]
		[SRDescription("ToolStripDropDownOpenedDescr")]
		public event EventHandler DropDownOpened
		{
			add
			{
				base.Events.AddHandler(ToolStripDropDownItem.EventDropDownOpened, value);
			}
			remove
			{
				base.Events.RemoveHandler(ToolStripDropDownItem.EventDropDownOpened, value);
			}
		}

		/// <summary>Gets the collection of items in the <see cref="T:System.Windows.Forms.ToolStripDropDown" /> that is associated with this <see cref="T:System.Windows.Forms.ToolStripDropDownItem" />.</summary>
		/// <returns>A <see cref="T:System.Windows.Forms.ToolStripItemCollection" /> of controls.</returns>
		// Token: 0x17000F7F RID: 3967
		// (get) Token: 0x06003E16 RID: 15894 RVA: 0x0010E461 File Offset: 0x0010C661
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[SRCategory("CatData")]
		[SRDescription("ToolStripDropDownItemsDescr")]
		public ToolStripItemCollection DropDownItems
		{
			get
			{
				return this.DropDown.Items;
			}
		}

		/// <summary>Occurs when the <see cref="T:System.Windows.Forms.ToolStripDropDown" /> is clicked.</summary>
		// Token: 0x14000327 RID: 807
		// (add) Token: 0x06003E17 RID: 15895 RVA: 0x0010E46E File Offset: 0x0010C66E
		// (remove) Token: 0x06003E18 RID: 15896 RVA: 0x0010E481 File Offset: 0x0010C681
		[SRCategory("CatAction")]
		public event ToolStripItemClickedEventHandler DropDownItemClicked
		{
			add
			{
				base.Events.AddHandler(ToolStripDropDownItem.EventDropDownItemClicked, value);
			}
			remove
			{
				base.Events.RemoveHandler(ToolStripDropDownItem.EventDropDownItemClicked, value);
			}
		}

		/// <summary>Gets a value indicating whether the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> has <see cref="T:System.Windows.Forms.ToolStripDropDown" /> controls associated with it. </summary>
		/// <returns>
		///     <see langword="true" /> if the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> has <see cref="T:System.Windows.Forms.ToolStripDropDown" /> controls; otherwise, <see langword="false" />.</returns>
		// Token: 0x17000F80 RID: 3968
		// (get) Token: 0x06003E19 RID: 15897 RVA: 0x0010E494 File Offset: 0x0010C694
		[Browsable(false)]
		public virtual bool HasDropDownItems
		{
			get
			{
				return this.dropDown != null && this.dropDown.HasVisibleItems;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the <see cref="P:System.Windows.Forms.ToolStripDropDownItem.DropDown" /> for the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> has been created.</summary>
		/// <returns>
		///     <see langword="true" /> if the <see cref="P:System.Windows.Forms.ToolStripDropDownItem.DropDown" /> for the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> has been created otherwise, <see langword="false" />.</returns>
		// Token: 0x17000F81 RID: 3969
		// (get) Token: 0x06003E1A RID: 15898 RVA: 0x0010E4AB File Offset: 0x0010C6AB
		[Browsable(false)]
		public bool HasDropDown
		{
			get
			{
				return this.dropDown != null;
			}
		}

		/// <summary>Gets a value indicating whether the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> is in the pressed state.</summary>
		/// <returns>
		///     <see langword="true" /> if the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> is in the pressed state; otherwise, <see langword="false" />. </returns>
		// Token: 0x17000F82 RID: 3970
		// (get) Token: 0x06003E1B RID: 15899 RVA: 0x0010E4B8 File Offset: 0x0010C6B8
		[Browsable(false)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
		public override bool Pressed
		{
			get
			{
				if (this.dropDown != null && (this.DropDown.AutoClose || !base.IsInDesignMode || (base.IsInDesignMode && !base.IsOnDropDown)))
				{
					return this.DropDown.OwnerItem == this && this.DropDown.Visible;
				}
				return base.Pressed;
			}
		}

		// Token: 0x17000F83 RID: 3971
		// (get) Token: 0x06003E1C RID: 15900 RVA: 0x0000E0A4 File Offset: 0x0000C2A4
		internal virtual bool OppositeDropDownAlign
		{
			get
			{
				return false;
			}
		}

		// Token: 0x06003E1D RID: 15901 RVA: 0x0010E514 File Offset: 0x0010C714
		internal virtual void AutoHide(ToolStripItem otherItemBeingSelected)
		{
			this.HideDropDown();
		}

		/// <summary>Creates a new accessibility object for the <see cref="T:System.Windows.Forms.ToolStripItem" />.</summary>
		/// <returns>A new <see cref="T:System.Windows.Forms.AccessibleObject" /> for the <see cref="T:System.Windows.Forms.ToolStripItem" />.</returns>
		// Token: 0x06003E1E RID: 15902 RVA: 0x0010E51C File Offset: 0x0010C71C
		protected override AccessibleObject CreateAccessibilityInstance()
		{
			return new ToolStripDropDownItemAccessibleObject(this);
		}

		/// <summary>Creates a generic <see cref="T:System.Windows.Forms.ToolStripDropDown" /> for which events can be defined.</summary>
		/// <returns>The created <see cref="T:System.Windows.Forms.ToolStripDropDown" /> object.</returns>
		// Token: 0x06003E1F RID: 15903 RVA: 0x0010E524 File Offset: 0x0010C724
		protected virtual ToolStripDropDown CreateDefaultDropDown()
		{
			return new ToolStripDropDown(this, true);
		}

		// Token: 0x06003E20 RID: 15904 RVA: 0x0010E530 File Offset: 0x0010C730
		private Rectangle DropDownDirectionToDropDownBounds(ToolStripDropDownDirection dropDownDirection, Rectangle dropDownBounds)
		{
			Point empty = Point.Empty;
			switch (dropDownDirection)
			{
			case ToolStripDropDownDirection.AboveLeft:
				empty.X = -dropDownBounds.Width + base.Width;
				empty.Y = -dropDownBounds.Height + 1;
				break;
			case ToolStripDropDownDirection.AboveRight:
				empty.Y = -dropDownBounds.Height + 1;
				break;
			case ToolStripDropDownDirection.BelowLeft:
				empty.X = -dropDownBounds.Width + base.Width;
				empty.Y = base.Height - 1;
				break;
			case ToolStripDropDownDirection.BelowRight:
				empty.Y = base.Height - 1;
				break;
			case ToolStripDropDownDirection.Left:
				empty.X = -dropDownBounds.Width;
				break;
			case ToolStripDropDownDirection.Right:
				empty.X = base.Width;
				if (!base.IsOnDropDown)
				{
					empty.X--;
				}
				break;
			}
			Point point = base.TranslatePoint(Point.Empty, ToolStripPointType.ToolStripItemCoords, ToolStripPointType.ScreenCoords);
			dropDownBounds.Location = new Point(point.X + empty.X, point.Y + empty.Y);
			dropDownBounds = WindowsFormsUtils.ConstrainToScreenWorkingAreaBounds(dropDownBounds);
			return dropDownBounds;
		}

		// Token: 0x06003E21 RID: 15905 RVA: 0x0010E653 File Offset: 0x0010C853
		private void DropDown_Closed(object sender, ToolStripDropDownClosedEventArgs e)
		{
			this.OnDropDownClosed(EventArgs.Empty);
		}

		// Token: 0x06003E22 RID: 15906 RVA: 0x0010E660 File Offset: 0x0010C860
		private void DropDown_Opened(object sender, EventArgs e)
		{
			this.OnDropDownOpened(EventArgs.Empty);
		}

		// Token: 0x06003E23 RID: 15907 RVA: 0x0010E66D File Offset: 0x0010C86D
		private void DropDown_ItemClicked(object sender, ToolStripItemClickedEventArgs e)
		{
			this.OnDropDownItemClicked(e);
		}

		/// <summary>Releases the unmanaged resources used by the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> and optionally releases the managed resources. </summary>
		/// <param name="disposing">
		///       <see langword="true" /> to release both managed and unmanaged resources; <see langword="false" /> to release only unmanaged resources. </param>
		// Token: 0x06003E24 RID: 15908 RVA: 0x0010E678 File Offset: 0x0010C878
		protected override void Dispose(bool disposing)
		{
			if (this.dropDown != null)
			{
				this.dropDown.Opened -= this.DropDown_Opened;
				this.dropDown.Closed -= this.DropDown_Closed;
				this.dropDown.ItemClicked -= this.DropDown_ItemClicked;
				if (disposing && this.dropDown.IsAutoGenerated)
				{
					this.dropDown.Dispose();
					this.dropDown = null;
				}
			}
			base.Dispose(disposing);
		}

		// Token: 0x06003E25 RID: 15909 RVA: 0x0010E6FC File Offset: 0x0010C8FC
		private Rectangle GetDropDownBounds(ToolStripDropDownDirection dropDownDirection)
		{
			Rectangle rectangle = new Rectangle(Point.Empty, this.DropDown.GetSuggestedSize());
			rectangle = this.DropDownDirectionToDropDownBounds(dropDownDirection, rectangle);
			Rectangle b = new Rectangle(base.TranslatePoint(Point.Empty, ToolStripPointType.ToolStripItemCoords, ToolStripPointType.ScreenCoords), this.Size);
			if (Rectangle.Intersect(rectangle, b).Height > 1)
			{
				bool flag = this.RightToLeft == RightToLeft.Yes;
				if (Rectangle.Intersect(rectangle, b).Width > 1)
				{
					rectangle = this.DropDownDirectionToDropDownBounds((!flag) ? ToolStripDropDownDirection.Right : ToolStripDropDownDirection.Left, rectangle);
				}
				if (Rectangle.Intersect(rectangle, b).Width > 1)
				{
					rectangle = this.DropDownDirectionToDropDownBounds((!flag) ? ToolStripDropDownDirection.Left : ToolStripDropDownDirection.Right, rectangle);
				}
			}
			return rectangle;
		}

		/// <summary>Makes a visible <see cref="T:System.Windows.Forms.ToolStripDropDown" /> hidden.</summary>
		// Token: 0x06003E26 RID: 15910 RVA: 0x0010E7A4 File Offset: 0x0010C9A4
		public void HideDropDown()
		{
			this.OnDropDownHide(EventArgs.Empty);
			if (this.dropDown != null && this.dropDown.Visible)
			{
				this.DropDown.Visible = false;
				if (AccessibilityImprovements.Level1)
				{
					base.AccessibilityNotifyClients(AccessibleEvents.StateChange);
					base.AccessibilityNotifyClients(AccessibleEvents.NameChange);
				}
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripDropDown.FontChanged" /> event.</summary>
		/// <param name="e">An <see cref="T:System.EventArgs" /> that contains the event data.</param>
		// Token: 0x06003E27 RID: 15911 RVA: 0x0010E7FA File Offset: 0x0010C9FA
		protected override void OnFontChanged(EventArgs e)
		{
			base.OnFontChanged(e);
			if (this.dropDown != null)
			{
				this.dropDown.OnOwnerItemFontChanged(EventArgs.Empty);
			}
		}

		/// <summary>Occurs when the <see cref="P:System.Windows.Forms.ToolStripItem.Bounds" /> property changes.</summary>
		// Token: 0x06003E28 RID: 15912 RVA: 0x0010E81B File Offset: 0x0010CA1B
		protected override void OnBoundsChanged()
		{
			base.OnBoundsChanged();
			if (this.dropDown != null && this.dropDown.Visible)
			{
				this.dropDown.Bounds = this.GetDropDownBounds(this.DropDownDirection);
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.Control.RightToLeftChanged" /> event.</summary>
		/// <param name="e">An <see cref="T:System.EventArgs" /> that contains the event data.</param>
		// Token: 0x06003E29 RID: 15913 RVA: 0x0010E850 File Offset: 0x0010CA50
		protected override void OnRightToLeftChanged(EventArgs e)
		{
			base.OnRightToLeftChanged(e);
			if (this.HasDropDownItems)
			{
				if (this.DropDown.Visible)
				{
					LayoutTransaction.DoLayout(this.DropDown, this, PropertyNames.RightToLeft);
					return;
				}
				CommonProperties.xClearPreferredSizeCache(this.DropDown);
				this.DropDown.LayoutRequired = true;
			}
		}

		// Token: 0x06003E2A RID: 15914 RVA: 0x0010E8A2 File Offset: 0x0010CAA2
		internal override void OnImageScalingSizeChanged(EventArgs e)
		{
			base.OnImageScalingSizeChanged(e);
			if (this.HasDropDown && this.DropDown.IsAutoGenerated)
			{
				this.DropDown.DoLayoutIfHandleCreated(new ToolStripItemEventArgs(this));
			}
		}

		/// <summary>Raised in response to the <see cref="M:System.Windows.Forms.ToolStripDropDownItem.HideDropDown" /> method.</summary>
		/// <param name="e">An <see cref="T:System.EventArgs" /> that contains the event data.</param>
		// Token: 0x06003E2B RID: 15915 RVA: 0x0010E8D4 File Offset: 0x0010CAD4
		protected virtual void OnDropDownHide(EventArgs e)
		{
			base.Invalidate();
			EventHandler eventHandler = (EventHandler)base.Events[ToolStripDropDownItem.EventDropDownHide];
			if (eventHandler != null)
			{
				eventHandler(this, e);
			}
		}

		/// <summary>Raised in response to the <see cref="M:System.Windows.Forms.ToolStripDropDownItem.ShowDropDown" /> method.</summary>
		/// <param name="e">An <see cref="T:System.EventArgs" /> that contains the event data.</param>
		// Token: 0x06003E2C RID: 15916 RVA: 0x0010E908 File Offset: 0x0010CB08
		protected virtual void OnDropDownShow(EventArgs e)
		{
			EventHandler eventHandler = (EventHandler)base.Events[ToolStripDropDownItem.EventDropDownShow];
			if (eventHandler != null)
			{
				eventHandler(this, e);
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripDropDownItem.DropDownOpened" /> event.</summary>
		/// <param name="e">An <see cref="T:System.EventArgs" /> that contains the event data. </param>
		// Token: 0x06003E2D RID: 15917 RVA: 0x0010E938 File Offset: 0x0010CB38
		protected internal virtual void OnDropDownOpened(EventArgs e)
		{
			if (this.DropDown.OwnerItem == this)
			{
				EventHandler eventHandler = (EventHandler)base.Events[ToolStripDropDownItem.EventDropDownOpened];
				if (eventHandler != null)
				{
					eventHandler(this, e);
				}
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripDropDownItem.DropDownClosed" /> event.</summary>
		/// <param name="e">An <see cref="T:System.EventArgs" /> that contains the event data. </param>
		// Token: 0x06003E2E RID: 15918 RVA: 0x0010E974 File Offset: 0x0010CB74
		protected internal virtual void OnDropDownClosed(EventArgs e)
		{
			base.Invalidate();
			if (this.DropDown.OwnerItem == this)
			{
				EventHandler eventHandler = (EventHandler)base.Events[ToolStripDropDownItem.EventDropDownClosed];
				if (eventHandler != null)
				{
					eventHandler(this, e);
				}
				if (!this.DropDown.IsAutoGenerated)
				{
					this.DropDown.OwnerItem = null;
				}
			}
		}

		/// <summary>Raises the <see cref="E:System.Windows.Forms.ToolStripDropDownItem.DropDownItemClicked" /> event.</summary>
		/// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemClickedEventArgs" /> that contains the event data.</param>
		// Token: 0x06003E2F RID: 15919 RVA: 0x0010E9D0 File Offset: 0x0010CBD0
		protected internal virtual void OnDropDownItemClicked(ToolStripItemClickedEventArgs e)
		{
			if (this.DropDown.OwnerItem == this)
			{
				ToolStripItemClickedEventHandler toolStripItemClickedEventHandler = (ToolStripItemClickedEventHandler)base.Events[ToolStripDropDownItem.EventDropDownItemClicked];
				if (toolStripItemClickedEventHandler != null)
				{
					toolStripItemClickedEventHandler(this, e);
				}
			}
		}

		/// <summary>Processes a command key.</summary>
		/// <param name="m">A <see cref="T:System.Windows.Forms.Message" />, passed by reference, that represents the window message to process. </param>
		/// <param name="keyData">One of the <see cref="T:System.Windows.Forms.Keys" /> values that represents the key to process. </param>
		/// <returns>
		///     <see langword="false" /> in all cases.</returns>
		// Token: 0x06003E30 RID: 15920 RVA: 0x0010EA0C File Offset: 0x0010CC0C
		[SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
		protected internal override bool ProcessCmdKey(ref Message m, Keys keyData)
		{
			if (this.HasDropDownItems)
			{
				return this.DropDown.ProcessCmdKeyInternal(ref m, keyData);
			}
			return base.ProcessCmdKey(ref m, keyData);
		}

		/// <summary>Processes a dialog key.</summary>
		/// <param name="keyData">One of the <see cref="T:System.Windows.Forms.Keys" /> values that represents the key to process. </param>
		/// <returns>
		///     <see langword="true" /> if the key was processed by the item; otherwise, <see langword="false" />.</returns>
		// Token: 0x06003E31 RID: 15921 RVA: 0x0010EA2C File Offset: 0x0010CC2C
		[UIPermission(SecurityAction.LinkDemand, Window = UIPermissionWindow.AllWindows)]
		protected internal override bool ProcessDialogKey(Keys keyData)
		{
			Keys keys = keyData & Keys.KeyCode;
			if (this.HasDropDownItems)
			{
				bool flag = !base.IsOnDropDown || base.IsOnOverflow;
				if (flag && (keys == Keys.Down || keys == Keys.Up || keys == Keys.Return || (base.SupportsSpaceKey && keys == Keys.Space)))
				{
					if (this.Enabled || base.DesignMode)
					{
						this.ShowDropDown();
						if (!AccessibilityImprovements.UseLegacyToolTipDisplay)
						{
							KeyboardToolTipStateMachine.Instance.NotifyAboutLostFocus(this);
						}
						this.DropDown.SelectNextToolStripItem(null, true);
					}
					return true;
				}
				if (!flag)
				{
					bool flag2 = (this.DropDownDirection & ToolStripDropDownDirection.AboveRight) == ToolStripDropDownDirection.AboveLeft;
					bool flag3 = keys == Keys.Return || (base.SupportsSpaceKey && keys == Keys.Space) || (flag2 && keys == Keys.Left) || (!flag2 && keys == Keys.Right);
					if (flag3)
					{
						if (this.Enabled || base.DesignMode)
						{
							this.ShowDropDown();
							if (!AccessibilityImprovements.UseLegacyToolTipDisplay)
							{
								KeyboardToolTipStateMachine.Instance.NotifyAboutLostFocus(this);
							}
							this.DropDown.SelectNextToolStripItem(null, true);
						}
						return true;
					}
				}
			}
			if (base.IsOnDropDown)
			{
				bool flag4 = (this.DropDownDirection & ToolStripDropDownDirection.AboveRight) == ToolStripDropDownDirection.AboveLeft;
				bool flag5 = (flag4 && keys == Keys.Right) || (!flag4 && keys == Keys.Left);
				if (flag5)
				{
					ToolStripDropDown currentParentDropDown = base.GetCurrentParentDropDown();
					if (currentParentDropDown != null && !currentParentDropDown.IsFirstDropDown)
					{
						currentParentDropDown.SetCloseReason(ToolStripDropDownCloseReason.Keyboard);
						if (!AccessibilityImprovements.UseLegacyToolTipDisplay)
						{
							KeyboardToolTipStateMachine.Instance.NotifyAboutLostFocus(this);
						}
						currentParentDropDown.SelectPreviousToolStrip();
						return true;
					}
				}
			}
			return base.ProcessDialogKey(keyData);
		}

		// Token: 0x06003E32 RID: 15922 RVA: 0x0010EBA4 File Offset: 0x0010CDA4
		private ToolStripDropDownDirection RTLTranslateDropDownDirection(ToolStripDropDownDirection dropDownDirection, RightToLeft rightToLeft)
		{
			switch (dropDownDirection)
			{
			case ToolStripDropDownDirection.AboveLeft:
				return ToolStripDropDownDirection.AboveRight;
			case ToolStripDropDownDirection.AboveRight:
				return ToolStripDropDownDirection.AboveLeft;
			case ToolStripDropDownDirection.BelowLeft:
				return ToolStripDropDownDirection.BelowRight;
			case ToolStripDropDownDirection.BelowRight:
				return ToolStripDropDownDirection.BelowLeft;
			case ToolStripDropDownDirection.Left:
				return ToolStripDropDownDirection.Right;
			case ToolStripDropDownDirection.Right:
				return ToolStripDropDownDirection.Left;
			default:
				if (base.IsOnDropDown)
				{
					if (rightToLeft != RightToLeft.Yes)
					{
						return ToolStripDropDownDirection.Right;
					}
					return ToolStripDropDownDirection.Left;
				}
				else
				{
					if (rightToLeft != RightToLeft.Yes)
					{
						return ToolStripDropDownDirection.BelowRight;
					}
					return ToolStripDropDownDirection.BelowLeft;
				}
				break;
			}
		}

		/// <summary>Displays the <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> control associated with this <see cref="T:System.Windows.Forms.ToolStripDropDownItem" />.</summary>
		/// <exception cref="T:System.InvalidOperationException">The <see cref="T:System.Windows.Forms.ToolStripDropDownItem" /> is the same as the parent <see cref="T:System.Windows.Forms.ToolStrip" />.</exception>
		// Token: 0x06003E33 RID: 15923 RVA: 0x0010EBF4 File Offset: 0x0010CDF4
		public void ShowDropDown()
		{
			this.ShowDropDown(false);
		}

		// Token: 0x06003E34 RID: 15924 RVA: 0x0010EC00 File Offset: 0x0010CE00
		internal void ShowDropDown(bool mousePush)
		{
			this.ShowDropDownInternal();
			ToolStripDropDownMenu toolStripDropDownMenu = this.dropDown as ToolStripDropDownMenu;
			if (toolStripDropDownMenu != null)
			{
				if (!mousePush)
				{
					toolStripDropDownMenu.ResetScrollPosition();
				}
				toolStripDropDownMenu.RestoreScrollPosition();
			}
		}

		// Token: 0x06003E35 RID: 15925 RVA: 0x0010EC34 File Offset: 0x0010CE34
		private void ShowDropDownInternal()
		{
			if (this.dropDown == null || !this.dropDown.Visible)
			{
				this.OnDropDownShow(EventArgs.Empty);
			}
			if (this.dropDown != null && !this.dropDown.Visible)
			{
				if (this.dropDown.IsAutoGenerated && this.DropDownItems.Count <= 0)
				{
					return;
				}
				if (this.DropDown == base.ParentInternal)
				{
					throw new InvalidOperationException(SR.GetString("ToolStripShowDropDownInvalidOperation"));
				}
				this.dropDown.OwnerItem = this;
				this.dropDown.Location = this.DropDownLocation;
				this.dropDown.Show();
				base.Invalidate();
				if (AccessibilityImprovements.Level1)
				{
					base.AccessibilityNotifyClients(AccessibleEvents.StateChange);
					base.AccessibilityNotifyClients(AccessibleEvents.NameChange);
				}
			}
		}

		// Token: 0x06003E36 RID: 15926 RVA: 0x0010ED01 File Offset: 0x0010CF01
		private bool ShouldSerializeDropDown()
		{
			return this.dropDown != null && !this.dropDown.IsAutoGenerated;
		}

		// Token: 0x06003E37 RID: 15927 RVA: 0x0010ED1B File Offset: 0x0010CF1B
		private bool ShouldSerializeDropDownDirection()
		{
			return this.toolStripDropDownDirection != ToolStripDropDownDirection.Default;
		}

		// Token: 0x06003E38 RID: 15928 RVA: 0x0010ED29 File Offset: 0x0010CF29
		private bool ShouldSerializeDropDownItems()
		{
			return this.dropDown != null && this.dropDown.IsAutoGenerated;
		}

		// Token: 0x06003E39 RID: 15929 RVA: 0x0010ED40 File Offset: 0x0010CF40
		internal override void OnKeyboardToolTipHook(ToolTip toolTip)
		{
			base.OnKeyboardToolTipHook(toolTip);
			KeyboardToolTipStateMachine.Instance.Hook(this.DropDown, toolTip);
		}

		// Token: 0x06003E3A RID: 15930 RVA: 0x0010ED5A File Offset: 0x0010CF5A
		internal override void OnKeyboardToolTipUnhook(ToolTip toolTip)
		{
			base.OnKeyboardToolTipUnhook(toolTip);
			KeyboardToolTipStateMachine.Instance.Unhook(this.DropDown, toolTip);
		}

		// Token: 0x06003E3B RID: 15931 RVA: 0x0010ED74 File Offset: 0x0010CF74
		internal override void ToolStrip_RescaleConstants(int oldDpi, int newDpi)
		{
			base.RescaleConstantsInternal(newDpi);
			Stack<ToolStripDropDownItem> stack = new Stack<ToolStripDropDownItem>();
			stack.Push(this);
			while (stack.Count > 0)
			{
				ToolStripDropDownItem toolStripDropDownItem = stack.Pop();
				if (toolStripDropDownItem.dropDown != null)
				{
					toolStripDropDownItem.dropDown.deviceDpi = newDpi;
					toolStripDropDownItem.dropDown.ResetScaling(newDpi);
					foreach (object obj in toolStripDropDownItem.DropDown.Items)
					{
						ToolStripItem toolStripItem = (ToolStripItem)obj;
						if (toolStripItem != null)
						{
							Font font = toolStripItem.Font;
							object obj2 = font;
							ToolStripItem ownerItem = toolStripItem.OwnerItem;
							if (!obj2.Equals((ownerItem != null) ? ownerItem.Font : null))
							{
								float num = (float)newDpi / (float)oldDpi;
								toolStripItem.Font = new Font(font.FontFamily, font.Size * num, font.Style, font.Unit, font.GdiCharSet, font.GdiVerticalFont);
							}
							toolStripItem.DeviceDpi = newDpi;
							if (typeof(ToolStripDropDownItem).IsAssignableFrom(toolStripItem.GetType()) && ((ToolStripDropDownItem)toolStripItem).dropDown != null)
							{
								stack.Push((ToolStripDropDownItem)toolStripItem);
							}
						}
					}
				}
			}
			base.ToolStrip_RescaleConstants(oldDpi, newDpi);
		}

		// Token: 0x040023E1 RID: 9185
		private ToolStripDropDown dropDown;

		// Token: 0x040023E2 RID: 9186
		private ToolStripDropDownDirection toolStripDropDownDirection = ToolStripDropDownDirection.Default;

		// Token: 0x040023E3 RID: 9187
		private static readonly object EventDropDownShow = new object();

		// Token: 0x040023E4 RID: 9188
		private static readonly object EventDropDownHide = new object();

		// Token: 0x040023E5 RID: 9189
		private static readonly object EventDropDownOpened = new object();

		// Token: 0x040023E6 RID: 9190
		private static readonly object EventDropDownClosed = new object();

		// Token: 0x040023E7 RID: 9191
		private static readonly object EventDropDownItemClicked = new object();
	}
}
