using System;
using System.Collections.Specialized;
using System.ComponentModel;

namespace System.Windows.Forms
{
	// Token: 0x020003E9 RID: 1001
	internal class ToolStripRendererSwitcher
	{
		// Token: 0x0600437D RID: 17277 RVA: 0x001216B8 File Offset: 0x0011F8B8
		public ToolStripRendererSwitcher(Control owner, ToolStripRenderMode defaultRenderMode) : this(owner)
		{
			this.defaultRenderMode = defaultRenderMode;
			this.RenderMode = defaultRenderMode;
		}

		// Token: 0x0600437E RID: 17278 RVA: 0x001216D0 File Offset: 0x0011F8D0
		public ToolStripRendererSwitcher(Control owner)
		{
			this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = true;
			this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged] = false;
			owner.Disposed += this.OnControlDisposed;
			owner.VisibleChanged += this.OnControlVisibleChanged;
			if (owner.Visible)
			{
				this.OnControlVisibleChanged(owner, EventArgs.Empty);
			}
		}

		// Token: 0x170010E0 RID: 4320
		// (get) Token: 0x0600437F RID: 17279 RVA: 0x00121754 File Offset: 0x0011F954
		// (set) Token: 0x06004380 RID: 17280 RVA: 0x001217A0 File Offset: 0x0011F9A0
		public ToolStripRenderer Renderer
		{
			get
			{
				if (this.RenderMode == ToolStripRenderMode.ManagerRenderMode)
				{
					return ToolStripManager.Renderer;
				}
				this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = false;
				if (this.renderer == null)
				{
					this.Renderer = ToolStripManager.CreateRenderer(this.RenderMode);
				}
				return this.renderer;
			}
			set
			{
				if (this.renderer != value)
				{
					this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = (value == null);
					this.renderer = value;
					this.currentRendererType = ((this.renderer != null) ? this.renderer.GetType() : typeof(Type));
					this.OnRendererChanged(EventArgs.Empty);
				}
			}
		}

		// Token: 0x170010E1 RID: 4321
		// (get) Token: 0x06004381 RID: 17281 RVA: 0x00121804 File Offset: 0x0011FA04
		// (set) Token: 0x06004382 RID: 17282 RVA: 0x00121868 File Offset: 0x0011FA68
		public ToolStripRenderMode RenderMode
		{
			get
			{
				if (this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer])
				{
					return ToolStripRenderMode.ManagerRenderMode;
				}
				if (this.renderer != null && !this.renderer.IsAutoGenerated)
				{
					return ToolStripRenderMode.Custom;
				}
				if (this.currentRendererType == ToolStripManager.ProfessionalRendererType)
				{
					return ToolStripRenderMode.Professional;
				}
				if (this.currentRendererType == ToolStripManager.SystemRendererType)
				{
					return ToolStripRenderMode.System;
				}
				return ToolStripRenderMode.Custom;
			}
			set
			{
				if (!ClientUtils.IsEnumValid(value, (int)value, 0, 3))
				{
					throw new InvalidEnumArgumentException("value", (int)value, typeof(ToolStripRenderMode));
				}
				if (value == ToolStripRenderMode.Custom)
				{
					throw new NotSupportedException(SR.GetString("ToolStripRenderModeUseRendererPropertyInstead"));
				}
				if (value == ToolStripRenderMode.ManagerRenderMode)
				{
					if (!this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer])
					{
						this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = true;
						this.OnRendererChanged(EventArgs.Empty);
						return;
					}
				}
				else
				{
					this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = false;
					this.Renderer = ToolStripManager.CreateRenderer(value);
				}
			}
		}

		// Token: 0x14000377 RID: 887
		// (add) Token: 0x06004383 RID: 17283 RVA: 0x00121900 File Offset: 0x0011FB00
		// (remove) Token: 0x06004384 RID: 17284 RVA: 0x00121938 File Offset: 0x0011FB38
		public event EventHandler RendererChanged;

		// Token: 0x06004385 RID: 17285 RVA: 0x0012196D File Offset: 0x0011FB6D
		private void OnRendererChanged(EventArgs e)
		{
			if (this.RendererChanged != null)
			{
				this.RendererChanged(this, e);
			}
		}

		// Token: 0x06004386 RID: 17286 RVA: 0x00121984 File Offset: 0x0011FB84
		private void OnDefaultRendererChanged(object sender, EventArgs e)
		{
			if (this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer])
			{
				this.OnRendererChanged(e);
			}
		}

		// Token: 0x06004387 RID: 17287 RVA: 0x0012199F File Offset: 0x0011FB9F
		private void OnControlDisposed(object sender, EventArgs e)
		{
			if (this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged])
			{
				ToolStripManager.RendererChanged -= this.OnDefaultRendererChanged;
				this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged] = false;
			}
		}

		// Token: 0x06004388 RID: 17288 RVA: 0x001219D8 File Offset: 0x0011FBD8
		private void OnControlVisibleChanged(object sender, EventArgs e)
		{
			Control control = sender as Control;
			if (control != null)
			{
				if (control.Visible)
				{
					if (!this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged])
					{
						ToolStripManager.RendererChanged += this.OnDefaultRendererChanged;
						this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged] = true;
						return;
					}
				}
				else if (this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged])
				{
					ToolStripManager.RendererChanged -= this.OnDefaultRendererChanged;
					this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged] = false;
				}
			}
		}

		// Token: 0x06004389 RID: 17289 RVA: 0x00121A60 File Offset: 0x0011FC60
		public bool ShouldSerializeRenderMode()
		{
			return this.RenderMode != this.defaultRenderMode && this.RenderMode > ToolStripRenderMode.Custom;
		}

		// Token: 0x0600438A RID: 17290 RVA: 0x00121A7B File Offset: 0x0011FC7B
		public void ResetRenderMode()
		{
			this.RenderMode = this.defaultRenderMode;
		}

		// Token: 0x04002598 RID: 9624
		private static readonly int stateUseDefaultRenderer = BitVector32.CreateMask();

		// Token: 0x04002599 RID: 9625
		private static readonly int stateAttachedRendererChanged = BitVector32.CreateMask(ToolStripRendererSwitcher.stateUseDefaultRenderer);

		// Token: 0x0400259A RID: 9626
		private ToolStripRenderer renderer;

		// Token: 0x0400259B RID: 9627
		private Type currentRendererType = typeof(Type);

		// Token: 0x0400259C RID: 9628
		private BitVector32 state;

		// Token: 0x0400259D RID: 9629
		private ToolStripRenderMode defaultRenderMode = ToolStripRenderMode.ManagerRenderMode;
	}
}
