using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x02000046 RID: 70
	internal enum IIDENTITYAUTHORITY_REFERENCE_IDENTITY_TO_TEXT_FLAGS
	{
		// Token: 0x04000138 RID: 312
		IIDENTITYAUTHORITY_REFERENCE_IDENTITY_TO_TEXT_FLAG_CANONICAL = 1
	}
}
