using System;
using System.Runtime.CompilerServices;

namespace System.Windows.Documents
{
	// Token: 0x020003A5 RID: 933
	internal static class RtfControls
	{
		// Token: 0x06003292 RID: 12946 RVA: 0x000DD66E File Offset: 0x000DB86E
		[MethodImpl(MethodImplOptions.NoInlining)]
		private static RtfControlWordInfo CreateCommonControlWord(string controlName, uint flags)
		{
			return new RtfControlWordInfo(RtfControlWord.Ctrl_Unknown, controlName, flags);
		}

		// Token: 0x06003293 RID: 12947 RVA: 0x000DD678 File Offset: 0x000DB878
		[MethodImpl(MethodImplOptions.NoInlining)]
		private static RtfControlWordInfo CreateCommonDocPropsControlWord(string controlName)
		{
			return new RtfControlWordInfo(RtfControlWord.Ctrl_Unknown, controlName, 8194U);
		}

		// Token: 0x06003294 RID: 12948 RVA: 0x000DD686 File Offset: 0x000DB886
		[MethodImpl(MethodImplOptions.NoInlining)]
		private static RtfControlWordInfo CreateCommonDrawObjControlWord(string controlName)
		{
			return new RtfControlWordInfo(RtfControlWord.Ctrl_Unknown, controlName, 536870914U);
		}

		// Token: 0x04001EDE RID: 7902
		public const uint RTK_TOGGLE = 1U;

		// Token: 0x04001EDF RID: 7903
		public const uint RTK_FLAG = 2U;

		// Token: 0x04001EE0 RID: 7904
		public const uint RTK_VALUE = 4U;

		// Token: 0x04001EE1 RID: 7905
		public const uint RTK_DESTINATION = 8U;

		// Token: 0x04001EE2 RID: 7906
		public const uint RTK_SYMBOL = 16U;

		// Token: 0x04001EE3 RID: 7907
		public const uint RTK_PARAM = 32U;

		// Token: 0x04001EE4 RID: 7908
		public const uint RTK_TEXT = 64U;

		// Token: 0x04001EE5 RID: 7909
		public const uint RTK_ACHARPROPS = 128U;

		// Token: 0x04001EE6 RID: 7910
		public const uint RTK_CHARPROPS = 256U;

		// Token: 0x04001EE7 RID: 7911
		public const uint RTK_PARAPROPS = 512U;

		// Token: 0x04001EE8 RID: 7912
		public const uint RTK_OBJPROPS = 1024U;

		// Token: 0x04001EE9 RID: 7913
		public const uint RTK_BOOKMARKPROPS = 2048U;

		// Token: 0x04001EEA RID: 7914
		public const uint RTK_SECTIONPROPS = 4096U;

		// Token: 0x04001EEB RID: 7915
		public const uint RTK_DOCPROPS = 8192U;

		// Token: 0x04001EEC RID: 7916
		public const uint RTK_FILEPROPS = 16384U;

		// Token: 0x04001EED RID: 7917
		public const uint RTK_COMMENT = 32768U;

		// Token: 0x04001EEE RID: 7918
		public const uint RTK_STYLE = 65536U;

		// Token: 0x04001EEF RID: 7919
		public const uint RTK_FONTTABLE = 131072U;

		// Token: 0x04001EF0 RID: 7920
		public const uint RTK_COLORTABLE = 262144U;

		// Token: 0x04001EF1 RID: 7921
		public const uint RTK_BULLETS = 524288U;

		// Token: 0x04001EF2 RID: 7922
		public const uint RTK_TABLEDEF = 1048576U;

		// Token: 0x04001EF3 RID: 7923
		public const uint RTK_SHAPES = 2097152U;

		// Token: 0x04001EF4 RID: 7924
		public const uint RTK_POSOBJ = 4194304U;

		// Token: 0x04001EF5 RID: 7925
		public const uint RTK_BORDER = 8388608U;

		// Token: 0x04001EF6 RID: 7926
		public const uint RTK_SHADING = 16777216U;

		// Token: 0x04001EF7 RID: 7927
		public const uint RTK_PICT = 33554432U;

		// Token: 0x04001EF8 RID: 7928
		public const uint RTK_FIELD = 67108864U;

		// Token: 0x04001EF9 RID: 7929
		public const uint RTK_FORMFIELD = 134217728U;

		// Token: 0x04001EFA RID: 7930
		public const uint RTK_INDEX = 268435456U;

		// Token: 0x04001EFB RID: 7931
		public const uint RTK_DRAWOBJ = 536870912U;

		// Token: 0x04001EFC RID: 7932
		public const uint RTK_INFO = 1073741824U;

		// Token: 0x04001EFD RID: 7933
		public const uint RTK_LISTTABLE = 2147483648U;

		// Token: 0x04001EFE RID: 7934
		public const uint RTK_PICTPROPS = 2147483648U;

		// Token: 0x04001EFF RID: 7935
		public const uint RTK_CHARSET = 2147483648U;

		// Token: 0x04001F00 RID: 7936
		public const uint RTK_UNICODE = 2147483648U;

		// Token: 0x04001F01 RID: 7937
		public const uint RTK_TABS = 2147483648U;

		// Token: 0x04001F02 RID: 7938
		public const uint RTK_FOOTNOTES = 2147483648U;

		// Token: 0x04001F03 RID: 7939
		public const uint RTK_HIGHLIGHT = 2147483648U;

		// Token: 0x04001F04 RID: 7940
		public const uint RTK_FILETABLE = 2147483648U;

		// Token: 0x04001F05 RID: 7941
		public const uint RTK_HEADER = 2147483648U;

		// Token: 0x04001F06 RID: 7942
		public const uint RTK_OBJECTS = 2147483648U;

		// Token: 0x04001F07 RID: 7943
		public const uint RTK_PARATEXT = 2147483648U;

		// Token: 0x04001F08 RID: 7944
		public const uint RTK_SPECIAL = 2147483648U;

		// Token: 0x04001F09 RID: 7945
		public const uint RTK_SECTION = 2147483648U;

		// Token: 0x04001F0A RID: 7946
		public const uint RTK_TOC = 2147483648U;

		// Token: 0x04001F0B RID: 7947
		internal static RtfControlWordInfo[] ControlTable = new RtfControlWordInfo[]
		{
			new RtfControlWordInfo(RtfControlWord.Ctrl_AB, "ab", 129U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ABSH, "absh", 4194308U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ABSLOCK, "abslock", 4194306U),
			RtfControls.CreateCommonControlWord("absnoovrlp", 4194337U),
			RtfControls.CreateCommonControlWord("absw", 4194308U),
			RtfControls.CreateCommonControlWord("acaps", 129U),
			RtfControls.CreateCommonControlWord("acccomma", 257U),
			RtfControls.CreateCommonControlWord("accdot", 257U),
			RtfControls.CreateCommonControlWord("accnone", 257U),
			RtfControls.CreateCommonControlWord("acf", 132U),
			RtfControls.CreateCommonControlWord("additive", 65538U),
			RtfControls.CreateCommonControlWord("adjustright", 4098U),
			RtfControls.CreateCommonControlWord("adn", 132U),
			RtfControls.CreateCommonDocPropsControlWord("aenddoc"),
			RtfControls.CreateCommonDocPropsControlWord("aendnotes"),
			RtfControls.CreateCommonControlWord("aexpnd", 132U),
			RtfControls.CreateCommonControlWord("af", 132U),
			RtfControls.CreateCommonControlWord("affixed", 514U),
			RtfControls.CreateCommonControlWord("afs", 132U),
			RtfControls.CreateCommonDocPropsControlWord("aftnbj"),
			RtfControls.CreateCommonControlWord("aftncn", 8200U),
			RtfControls.CreateCommonDocPropsControlWord("aftnnalc"),
			RtfControls.CreateCommonDocPropsControlWord("aftnnar"),
			RtfControls.CreateCommonDocPropsControlWord("aftnnauc"),
			RtfControls.CreateCommonDocPropsControlWord("aftnnchi"),
			RtfControls.CreateCommonDocPropsControlWord("aftnnchosung"),
			RtfControls.CreateCommonDocPropsControlWord("aftnncnum"),
			RtfControls.CreateCommonDocPropsControlWord("aftnndbar"),
			RtfControls.CreateCommonDocPropsControlWord("aftnndbnum"),
			RtfControls.CreateCommonDocPropsControlWord("aftnndbnumd"),
			RtfControls.CreateCommonDocPropsControlWord("aftnndbnumk"),
			RtfControls.CreateCommonDocPropsControlWord("aftnndbnumt"),
			RtfControls.CreateCommonDocPropsControlWord("aftnnganada"),
			RtfControls.CreateCommonDocPropsControlWord("aftnngbnum"),
			RtfControls.CreateCommonDocPropsControlWord("aftnngbnumd"),
			RtfControls.CreateCommonDocPropsControlWord("aftnngbnumk"),
			RtfControls.CreateCommonDocPropsControlWord("aftnngbnuml"),
			RtfControls.CreateCommonDocPropsControlWord("aftnnrlc"),
			RtfControls.CreateCommonDocPropsControlWord("aftnnruc"),
			RtfControls.CreateCommonDocPropsControlWord("aftnnzodiac"),
			RtfControls.CreateCommonDocPropsControlWord("aftnnzodiacd"),
			RtfControls.CreateCommonDocPropsControlWord("aftnnzodiacl"),
			RtfControls.CreateCommonDocPropsControlWord("aftnrestart"),
			RtfControls.CreateCommonDocPropsControlWord("aftnrstcont"),
			RtfControls.CreateCommonControlWord("aftnsep", 8200U),
			RtfControls.CreateCommonControlWord("aftnsepc", 8200U),
			RtfControls.CreateCommonControlWord("aftnstart", 8196U),
			RtfControls.CreateCommonDocPropsControlWord("aftntj"),
			RtfControls.CreateCommonControlWord("ai", 129U),
			RtfControls.CreateCommonControlWord("alang", 132U),
			RtfControls.CreateCommonDocPropsControlWord("allprot"),
			RtfControls.CreateCommonDocPropsControlWord("alntblind"),
			RtfControls.CreateCommonControlWord("alt", 65538U),
			RtfControls.CreateCommonControlWord("animtext", 292U),
			RtfControls.CreateCommonControlWord("annotation", 32776U),
			RtfControls.CreateCommonDocPropsControlWord("annotprot"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ANSI, "ansi", 8194U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ANSICPG, "ansicpg", 8228U),
			RtfControls.CreateCommonControlWord("aoutl", 129U),
			RtfControls.CreateCommonControlWord("ascaps", 129U),
			RtfControls.CreateCommonControlWord("ashad", 129U),
			RtfControls.CreateCommonControlWord("aspalpha", 513U),
			RtfControls.CreateCommonControlWord("aspnum", 513U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ASTRIKE, "astrike", 129U),
			RtfControls.CreateCommonControlWord("atnauthor", 32776U),
			RtfControls.CreateCommonControlWord("atnicn", 32776U),
			RtfControls.CreateCommonControlWord("atnid", 32776U),
			RtfControls.CreateCommonControlWord("atnref", 32776U),
			RtfControls.CreateCommonControlWord("atntime", 32776U),
			RtfControls.CreateCommonControlWord("atrfend", 32776U),
			RtfControls.CreateCommonControlWord("atrfstart", 32776U),
			RtfControls.CreateCommonControlWord("aul", 129U),
			RtfControls.CreateCommonControlWord("auld", 129U),
			RtfControls.CreateCommonControlWord("auldb", 129U),
			RtfControls.CreateCommonControlWord("aulnone", 129U),
			RtfControls.CreateCommonControlWord("aulw", 129U),
			RtfControls.CreateCommonControlWord("aup", 132U),
			RtfControls.CreateCommonControlWord("author", 1073741832U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_B, "b", 257U),
			RtfControls.CreateCommonControlWord("background", 2097160U),
			RtfControls.CreateCommonDocPropsControlWord("bdbfhdr"),
			RtfControls.CreateCommonDocPropsControlWord("bdrrlswsix"),
			RtfControls.CreateCommonControlWord("bgbdiag", 16777730U),
			RtfControls.CreateCommonControlWord("bgcross", 16777730U),
			RtfControls.CreateCommonControlWord("bgdcross", 16777730U),
			RtfControls.CreateCommonControlWord("bgdkbdiag", 16777730U),
			RtfControls.CreateCommonControlWord("bgdkcross", 16777730U),
			RtfControls.CreateCommonControlWord("bgdkdcross", 16777730U),
			RtfControls.CreateCommonControlWord("bgdkfdiag", 16777730U),
			RtfControls.CreateCommonControlWord("bgdkhoriz", 16777730U),
			RtfControls.CreateCommonControlWord("bgdkvert", 16777730U),
			RtfControls.CreateCommonControlWord("bgfdiag", 16777730U),
			RtfControls.CreateCommonControlWord("bghoriz", 16777730U),
			RtfControls.CreateCommonControlWord("bgvert", 16777730U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BIN, "bin", 2147483652U),
			RtfControls.CreateCommonControlWord("binfsxn", 4100U),
			RtfControls.CreateCommonControlWord("binsxn", 4100U),
			RtfControls.CreateCommonControlWord("bkmkcolf", 2052U),
			RtfControls.CreateCommonControlWord("bkmkcoll", 2052U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BKMKEND, "bkmkend", 2056U),
			RtfControls.CreateCommonControlWord("bkmkpub", 1026U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BKMKSTART, "bkmkstart", 2056U),
			RtfControls.CreateCommonControlWord("bliptag", 2147483684U),
			RtfControls.CreateCommonControlWord("blipuid", 2147483652U),
			RtfControls.CreateCommonControlWord("blipupi", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BLUE, "blue", 262148U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BOX, "box", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRART, "brdrart", 8228U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRB, "brdrb", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRBAR, "brdrbar", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRBTW, "brdrbtw", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRCF, "brdrcf", 8389124U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDASH, "brdrdash", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDASHD, "brdrdashd", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDASHDD, "brdrdashdd", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDASHDOTSTR, "brdrdashdotstr", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDASHSM, "brdrdashsm", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDB, "brdrdb", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDOT, "brdrdot", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDREMBOSS, "brdremboss", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRENGRAVE, "brdrengrave", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRFRAME, "brdrframe", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRHAIR, "brdrhair", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRINSET, "brdrinset", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRL, "brdrl", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDROUTSET, "brdroutset", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRNIL, "brdrnil", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTBL, "brdrtbl", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRR, "brdrr", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRS, "brdrs", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRSH, "brdrsh", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRT, "brdrt", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTH, "brdrth", 8389122U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTHTNLG, "brdrthtnlg", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTHTNMG, "brdrthtnmg", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTHTNSG, "brdrthtnsg", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTNTHLG, "brdrtnthlg", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTNTHMG, "brdrtnthmg", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTNTHSG, "brdrtnthsg", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTNTHTNLG, "brdrtnthtnlg", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTNTHTNMG, "brdrtnthtnmg", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTNTHTNSG, "brdrtnthtnsg", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTRIPLE, "brdrtriple", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRW, "brdrw", 8389124U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRWAVY, "brdrwavy", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRWAVYDB, "brdrwavydb", 578U),
			RtfControls.CreateCommonDocPropsControlWord("brkfrm"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BRSP, "brsp", 8389124U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_BULLET, "bullet", 16U),
			RtfControls.CreateCommonControlWord("buptim", 1073741832U),
			RtfControls.CreateCommonControlWord("bxe", 268435458U),
			RtfControls.CreateCommonControlWord("caps", 257U),
			RtfControls.CreateCommonControlWord("category", 1073741832U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CB, "cb", 260U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CBPAT, "cbpat", 16777732U),
			RtfControls.CreateCommonControlWord("cchs", 260U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CELL, "cell", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CELLX, "cellx", 1048580U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CF, "cf", 260U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CFPAT, "cfpat", 16777732U),
			RtfControls.CreateCommonControlWord("cgrid", 292U),
			RtfControls.CreateCommonControlWord("charscalex", 16777508U),
			RtfControls.CreateCommonControlWord("chatn", 16U),
			RtfControls.CreateCommonControlWord("chbgbdiag", 16777474U),
			RtfControls.CreateCommonControlWord("chbgcross", 16777474U),
			RtfControls.CreateCommonControlWord("chbgdcross", 16777474U),
			RtfControls.CreateCommonControlWord("chbgdkbdiag", 16777474U),
			RtfControls.CreateCommonControlWord("chbgdkcross", 16777474U),
			RtfControls.CreateCommonControlWord("chbgdkdcross", 16777474U),
			RtfControls.CreateCommonControlWord("chbgdkfdiag", 16777474U),
			RtfControls.CreateCommonControlWord("chbgdkhoriz", 16777474U),
			RtfControls.CreateCommonControlWord("chbgdkvert", 16777474U),
			RtfControls.CreateCommonControlWord("chbgfdiag", 16777474U),
			RtfControls.CreateCommonControlWord("chbghoriz", 16777474U),
			RtfControls.CreateCommonControlWord("chbgvert", 16777474U),
			RtfControls.CreateCommonControlWord("chbrdr", 16777474U),
			RtfControls.CreateCommonControlWord("chcbpat", 16777508U),
			RtfControls.CreateCommonControlWord("chcfpat", 16777508U),
			RtfControls.CreateCommonControlWord("chdate", 16U),
			RtfControls.CreateCommonControlWord("chdpa", 16U),
			RtfControls.CreateCommonControlWord("chdpl", 16U),
			RtfControls.CreateCommonControlWord("chftn", 16U),
			RtfControls.CreateCommonControlWord("chftnsep", 16U),
			RtfControls.CreateCommonControlWord("chftnsepc", 16U),
			RtfControls.CreateCommonControlWord("chpgn", 16U),
			RtfControls.CreateCommonControlWord("chshdng", 16777508U),
			RtfControls.CreateCommonControlWord("chtime", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGBDIAG, "clbgbdiag", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGCROSS, "clbgcross", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDCROSS, "clbgdcross", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDKBDIAG, "clbgdkbdiag", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDKCROSS, "clbgdkcross", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDKDCROSS, "clbgdkdcross", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDKFDIAG, "clbgdkfdiag", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDKHOR, "clbgdkhor", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDKVERT, "clbgdkvert", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGFDIAG, "clbgfdiag", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGHORIZ, "clbghoriz", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGVERT, "clbgvert", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBRDRB, "clbrdrb", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBRDRL, "clbrdrl", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBRDRR, "clbrdrr", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLBRDRT, "clbrdrt", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLCBPAT, "clcbpat", 1048580U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLCFPAT, "clcfpat", 1048580U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLDGLL, "cldgll", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLDGLU, "cldglu", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLFITTEXT, "clfittext", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLFTSWIDTH, "clftswidth", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLMGF, "clmgf", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLMRG, "clmrg", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLOWRAP, "clowrap", 1048610U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADB, "clpadb", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADFB, "clpadfb", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADFL, "clpadfl", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADFR, "clpadfr", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADFT, "clpadft", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADL, "clpadl", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADR, "clpadr", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADT, "clpadt", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLSHDNG, "clshdng", 1048580U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLSHDRAWNIL, "clshdrawnil", 1048580U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLTXBTLR, "cltxbtlr", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLTXLRTB, "cltxlrtb", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLTXLRTBV, "cltxlrtbv", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLTXTBRL, "cltxtbrl", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLTXTBRLV, "cltxtbrlv", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLVERTALB, "clvertalb", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLVERTALC, "clvertalc", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLVERTALT, "clvertalt", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLVMGF, "clvmgf", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLVMRG, "clvmrg", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_CLWWIDTH, "clwwidth", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_COLLAPSED, "collapsed", 514U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_COLNO, "colno", 4100U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_COLORTBL, "colortbl", 262152U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_COLS, "cols", 4100U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_COLSR, "colsr", 4100U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_COLSX, "colsx", 4100U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_COLUMN, "column", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_COLW, "colw", 4100U),
			RtfControls.CreateCommonControlWord("comment", 1073741832U),
			RtfControls.CreateCommonControlWord("company", 1073741832U),
			RtfControls.CreateCommonControlWord("cpg", 2147483652U),
			RtfControls.CreateCommonControlWord("crauth", 16777508U),
			RtfControls.CreateCommonControlWord("crdate", 16777508U),
			RtfControls.CreateCommonControlWord("creatim", 1073741832U),
			RtfControls.CreateCommonControlWord("cs", 260U),
			RtfControls.CreateCommonControlWord("ctrl", 65538U),
			RtfControls.CreateCommonControlWord("cts", 8228U),
			RtfControls.CreateCommonControlWord("cufi", 548U),
			RtfControls.CreateCommonControlWord("culi", 548U),
			RtfControls.CreateCommonControlWord("curi", 548U),
			RtfControls.CreateCommonDocPropsControlWord("cvmme"),
			RtfControls.CreateCommonControlWord("datafield", 67108872U),
			RtfControls.CreateCommonControlWord("date", 67108866U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_DBCH, "dbch", 130U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_DEFF, "deff", 131076U),
			RtfControls.CreateCommonDocPropsControlWord("defformat"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_DEFLANG, "deflang", 8196U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_DEFLANGA, "deflanga", 8196U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_DEFLANGFE, "deflangfe", 8196U),
			RtfControls.CreateCommonControlWord("defshp", 33554434U),
			RtfControls.CreateCommonControlWord("deftab", 8196U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_DELETED, "deleted", 257U),
			RtfControls.CreateCommonControlWord("dfrauth", 2147483684U),
			RtfControls.CreateCommonControlWord("dfrdate", 2147483684U),
			RtfControls.CreateCommonControlWord("dfrmtxtx", 4194308U),
			RtfControls.CreateCommonControlWord("dfrmtxty", 4194308U),
			RtfControls.CreateCommonControlWord("dfrstart", 2147483652U),
			RtfControls.CreateCommonControlWord("dfrstop", 2147483652U),
			RtfControls.CreateCommonControlWord("dfrxst", 2147483652U),
			RtfControls.CreateCommonControlWord("dghorigin", 8228U),
			RtfControls.CreateCommonControlWord("dghshow", 8228U),
			RtfControls.CreateCommonControlWord("dghspace", 8228U),
			RtfControls.CreateCommonDocPropsControlWord("dgmargin"),
			RtfControls.CreateCommonDocPropsControlWord("dgsnap"),
			RtfControls.CreateCommonControlWord("dgvorigin", 8228U),
			RtfControls.CreateCommonControlWord("dgvshow", 8228U),
			RtfControls.CreateCommonControlWord("dgvspace", 8228U),
			RtfControls.CreateCommonControlWord("dibitmap", 2147483652U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_DN, "dn", 2147483652U),
			RtfControls.CreateCommonDocPropsControlWord("dntblnsbdb"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_DO, "do", 536870920U),
			RtfControls.CreateCommonDrawObjControlWord("dobxcolumn"),
			RtfControls.CreateCommonDrawObjControlWord("dobxmargin"),
			RtfControls.CreateCommonDrawObjControlWord("dobxpage"),
			RtfControls.CreateCommonDrawObjControlWord("dobymargin"),
			RtfControls.CreateCommonDrawObjControlWord("dobypage"),
			RtfControls.CreateCommonDrawObjControlWord("dobypara"),
			RtfControls.CreateCommonControlWord("doccomm", 1073741832U),
			RtfControls.CreateCommonDocPropsControlWord("doctemp"),
			RtfControls.CreateCommonControlWord("doctype", 8228U),
			RtfControls.CreateCommonControlWord("docvar", 8200U),
			RtfControls.CreateCommonControlWord("dodhgt", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dolock"),
			RtfControls.CreateCommonDrawObjControlWord("dpaendhol"),
			RtfControls.CreateCommonControlWord("dpaendl", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dpaendsol"),
			RtfControls.CreateCommonControlWord("dpaendw", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dparc"),
			RtfControls.CreateCommonDrawObjControlWord("dparcflipx"),
			RtfControls.CreateCommonDrawObjControlWord("dparcflipy"),
			RtfControls.CreateCommonDrawObjControlWord("dpastarthol"),
			RtfControls.CreateCommonControlWord("dpastartl", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dpastartsol"),
			RtfControls.CreateCommonControlWord("dpastartw", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dpcallout"),
			RtfControls.CreateCommonControlWord("dpcoa", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dpcoaccent"),
			RtfControls.CreateCommonDrawObjControlWord("dpcobestfit"),
			RtfControls.CreateCommonDrawObjControlWord("dpcoborder"),
			RtfControls.CreateCommonControlWord("dpcodabs", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dpcodbottom"),
			RtfControls.CreateCommonDrawObjControlWord("dpcodcenter"),
			RtfControls.CreateCommonControlWord("dpcodescent", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dpcodtop"),
			RtfControls.CreateCommonControlWord("dpcolength", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dpcominusx"),
			RtfControls.CreateCommonDrawObjControlWord("dpcominusy"),
			RtfControls.CreateCommonControlWord("dpcooffset", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dpcosmarta"),
			RtfControls.CreateCommonDrawObjControlWord("dpcotdouble"),
			RtfControls.CreateCommonDrawObjControlWord("dpcotright"),
			RtfControls.CreateCommonDrawObjControlWord("dpcotsingle"),
			RtfControls.CreateCommonDrawObjControlWord("dpcottriple"),
			RtfControls.CreateCommonControlWord("dpcount", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dpellipse"),
			RtfControls.CreateCommonDrawObjControlWord("dpendgroup"),
			RtfControls.CreateCommonControlWord("dpfillbgcb", 536870916U),
			RtfControls.CreateCommonControlWord("dpfillbgcg", 536870916U),
			RtfControls.CreateCommonControlWord("dpfillbgcr", 536870916U),
			RtfControls.CreateCommonControlWord("dpfillbggray", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dpfillbgpal"),
			RtfControls.CreateCommonControlWord("dpfillfgcb", 536870916U),
			RtfControls.CreateCommonControlWord("dpfillfgcg", 536870916U),
			RtfControls.CreateCommonControlWord("dpfillfgcr", 536870916U),
			RtfControls.CreateCommonControlWord("dpfillfggray", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dpfillfgpal"),
			RtfControls.CreateCommonControlWord("dpfillpat", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dpgroup"),
			RtfControls.CreateCommonDrawObjControlWord("dpline"),
			RtfControls.CreateCommonControlWord("dplinecob", 536870916U),
			RtfControls.CreateCommonControlWord("dplinecog", 536870916U),
			RtfControls.CreateCommonControlWord("dplinecor", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dplinedado"),
			RtfControls.CreateCommonDrawObjControlWord("dplinedadodo"),
			RtfControls.CreateCommonDrawObjControlWord("dplinedash"),
			RtfControls.CreateCommonDrawObjControlWord("dplinedot"),
			RtfControls.CreateCommonControlWord("dplinegray", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dplinehollow"),
			RtfControls.CreateCommonDrawObjControlWord("dplinepal"),
			RtfControls.CreateCommonDrawObjControlWord("dplinesolid"),
			RtfControls.CreateCommonControlWord("dplinew", 536870916U),
			RtfControls.CreateCommonControlWord("dppolycount", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dppolygon"),
			RtfControls.CreateCommonDrawObjControlWord("dppolyline"),
			RtfControls.CreateCommonControlWord("dpptx", 536870916U),
			RtfControls.CreateCommonControlWord("dppty", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dprect"),
			RtfControls.CreateCommonDrawObjControlWord("dproundr"),
			RtfControls.CreateCommonDrawObjControlWord("dpshadow"),
			RtfControls.CreateCommonControlWord("dpshadx", 536870916U),
			RtfControls.CreateCommonControlWord("dpshady", 536870916U),
			RtfControls.CreateCommonDrawObjControlWord("dptxbtlr"),
			RtfControls.CreateCommonDrawObjControlWord("dptxbx"),
			RtfControls.CreateCommonControlWord("dptxbxmar", 536870916U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_DPTXBXTEXT, "dptxbxtext", 536870920U),
			RtfControls.CreateCommonDrawObjControlWord("dptxlrtb"),
			RtfControls.CreateCommonDrawObjControlWord("dptxlrtbv"),
			RtfControls.CreateCommonDrawObjControlWord("dptxtbrl"),
			RtfControls.CreateCommonDrawObjControlWord("dptxtbrlv"),
			RtfControls.CreateCommonControlWord("dpx", 536870916U),
			RtfControls.CreateCommonControlWord("dpxsize", 536870916U),
			RtfControls.CreateCommonControlWord("dpy", 536870916U),
			RtfControls.CreateCommonControlWord("dpysize", 536870916U),
			RtfControls.CreateCommonControlWord("dropcapli", 4194308U),
			RtfControls.CreateCommonControlWord("dropcapt", 4194308U),
			RtfControls.CreateCommonControlWord("ds", 4100U),
			RtfControls.CreateCommonControlWord("dxfrtext", 4194308U),
			RtfControls.CreateCommonControlWord("dy", 1073741828U),
			RtfControls.CreateCommonControlWord("edmins", 1073741828U),
			RtfControls.CreateCommonControlWord("embo", 16777473U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_EMDASH, "emdash", 16U),
			RtfControls.CreateCommonControlWord("emfblip", 33554434U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_EMSPACE, "emspace", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ENDASH, "endash", 16U),
			RtfControls.CreateCommonDocPropsControlWord("enddoc"),
			RtfControls.CreateCommonControlWord("endnhere", 4098U),
			RtfControls.CreateCommonDocPropsControlWord("endnotes"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ENSPACE, "enspace", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_EXPND, "expnd", 260U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_EXPNDTW, "expndtw", 260U),
			RtfControls.CreateCommonDocPropsControlWord("expshrtn"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_F, "f", 260U),
			RtfControls.CreateCommonControlWord("faauto", 516U),
			RtfControls.CreateCommonControlWord("facenter", 514U),
			RtfControls.CreateCommonDocPropsControlWord("facingp"),
			RtfControls.CreateCommonControlWord("fahang", 514U),
			RtfControls.CreateCommonControlWord("falt", 131080U),
			RtfControls.CreateCommonControlWord("faroman", 514U),
			RtfControls.CreateCommonControlWord("favar", 514U),
			RtfControls.CreateCommonControlWord("fbias", 131108U),
			RtfControls.CreateCommonControlWord("fbidi", 131074U),
			RtfControls.CreateCommonControlWord("fchars", 8200U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FCHARSET, "fcharset", 131076U),
			RtfControls.CreateCommonControlWord("fdecor", 131074U),
			RtfControls.CreateCommonControlWord("fet", 8196U),
			RtfControls.CreateCommonControlWord("fetch", 131074U),
			RtfControls.CreateCommonControlWord("ffdefres", 134217732U),
			RtfControls.CreateCommonControlWord("ffdeftext", 134217736U),
			RtfControls.CreateCommonControlWord("ffentrymcr", 134217736U),
			RtfControls.CreateCommonControlWord("ffexitmcr", 134217736U),
			RtfControls.CreateCommonControlWord("ffformat", 134217736U),
			RtfControls.CreateCommonControlWord("ffhaslistbox", 134217764U),
			RtfControls.CreateCommonControlWord("ffhelptext", 134217736U),
			RtfControls.CreateCommonControlWord("ffhps", 134217764U),
			RtfControls.CreateCommonControlWord("ffl", 134217736U),
			RtfControls.CreateCommonControlWord("ffmaxlen", 134217732U),
			RtfControls.CreateCommonControlWord("ffname", 134217736U),
			RtfControls.CreateCommonControlWord("ffownhelp", 134217764U),
			RtfControls.CreateCommonControlWord("ffownstat", 134217764U),
			RtfControls.CreateCommonControlWord("ffprot", 134217764U),
			RtfControls.CreateCommonControlWord("ffrecalc", 134217764U),
			RtfControls.CreateCommonControlWord("ffres", 134217764U),
			RtfControls.CreateCommonControlWord("ffsize", 134217764U),
			RtfControls.CreateCommonControlWord("ffstattext", 134217736U),
			RtfControls.CreateCommonControlWord("fftype", 134217764U),
			RtfControls.CreateCommonControlWord("fftypetxt", 134217764U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FI, "fi", 516U),
			RtfControls.CreateCommonControlWord("fid", 2147483652U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FIELD, "field", 67108872U),
			RtfControls.CreateCommonControlWord("file", 2147483656U),
			RtfControls.CreateCommonControlWord("filetbl", 2147483656U),
			RtfControls.CreateCommonControlWord("fittext", 292U),
			RtfControls.CreateCommonDocPropsControlWord("fldalt"),
			RtfControls.CreateCommonControlWord("flddirty", 67108866U),
			RtfControls.CreateCommonControlWord("fldedit", 67108866U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FLDINST, "fldinst", 67108872U),
			RtfControls.CreateCommonControlWord("fldlock", 67108866U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FLDPRIV, "fldpriv", 67108866U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FLDRSLT, "fldrslt", 67108872U),
			RtfControls.CreateCommonControlWord("fldtype", 67108872U),
			RtfControls.CreateCommonControlWord("fmodern", 131074U),
			RtfControls.CreateCommonControlWord("fn", 65540U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FNAME, "fname", 131080U),
			RtfControls.CreateCommonControlWord("fnetwork", 2147483650U),
			RtfControls.CreateCommonControlWord("fnil", 2147483650U),
			RtfControls.CreateCommonControlWord("fontemb", 131080U),
			RtfControls.CreateCommonControlWord("fontfile", 131080U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FONTTBL, "fonttbl", 131080U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FOOTER, "footer", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FOOTERF, "footerf", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FOOTERL, "footerl", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FOOTERR, "footerr", 2147483656U),
			RtfControls.CreateCommonControlWord("footery", 4100U),
			RtfControls.CreateCommonControlWord("footnote", 2147483656U),
			RtfControls.CreateCommonDocPropsControlWord("formdisp"),
			RtfControls.CreateCommonControlWord("formfield", 134217736U),
			RtfControls.CreateCommonDocPropsControlWord("formprot"),
			RtfControls.CreateCommonDocPropsControlWord("formshade"),
			RtfControls.CreateCommonControlWord("fosnum", 2147483652U),
			RtfControls.CreateCommonControlWord("fprq", 131076U),
			RtfControls.CreateCommonDocPropsControlWord("fracwidth"),
			RtfControls.CreateCommonControlWord("frelative", 2147483652U),
			RtfControls.CreateCommonControlWord("frmtxbtlr", 4194306U),
			RtfControls.CreateCommonControlWord("frmtxlrtb", 4194306U),
			RtfControls.CreateCommonControlWord("frmtxlrtbv", 4194306U),
			RtfControls.CreateCommonControlWord("frmtxtbrl", 4194306U),
			RtfControls.CreateCommonControlWord("frmtxtbrlv", 4194306U),
			RtfControls.CreateCommonControlWord("froman", 131074U),
			RtfControls.CreateCommonDocPropsControlWord("fromhtml"),
			RtfControls.CreateCommonDocPropsControlWord("fromtext"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_FS, "fs", 260U),
			RtfControls.CreateCommonControlWord("fscript", 131074U),
			RtfControls.CreateCommonControlWord("fswiss", 131074U),
			RtfControls.CreateCommonDocPropsControlWord("ftnalt"),
			RtfControls.CreateCommonDocPropsControlWord("ftnbj"),
			RtfControls.CreateCommonControlWord("ftncn", 8200U),
			RtfControls.CreateCommonControlWord("ftnil", 131074U),
			RtfControls.CreateCommonDocPropsControlWord("ftnlytwnine"),
			RtfControls.CreateCommonDocPropsControlWord("ftnnalc"),
			RtfControls.CreateCommonDocPropsControlWord("ftnnar"),
			RtfControls.CreateCommonDocPropsControlWord("ftnnauc"),
			RtfControls.CreateCommonDocPropsControlWord("ftnnchi"),
			RtfControls.CreateCommonDocPropsControlWord("ftnnchosung"),
			RtfControls.CreateCommonDocPropsControlWord("ftnncnum"),
			RtfControls.CreateCommonDocPropsControlWord("ftnndbar"),
			RtfControls.CreateCommonDocPropsControlWord("ftnndbnum"),
			RtfControls.CreateCommonDocPropsControlWord("ftnndbnumd"),
			RtfControls.CreateCommonDocPropsControlWord("ftnndbnumk"),
			RtfControls.CreateCommonDocPropsControlWord("ftnndbnumt"),
			RtfControls.CreateCommonDocPropsControlWord("ftnnganada"),
			RtfControls.CreateCommonDocPropsControlWord("ftnngbnum"),
			RtfControls.CreateCommonDocPropsControlWord("ftnngbnumd"),
			RtfControls.CreateCommonDocPropsControlWord("ftnngbnumk"),
			RtfControls.CreateCommonDocPropsControlWord("ftnngbnuml"),
			RtfControls.CreateCommonDocPropsControlWord("ftnnrlc"),
			RtfControls.CreateCommonDocPropsControlWord("ftnnruc"),
			RtfControls.CreateCommonDocPropsControlWord("ftnnzodiac"),
			RtfControls.CreateCommonDocPropsControlWord("ftnnzodiacd"),
			RtfControls.CreateCommonDocPropsControlWord("ftnnzodiacl"),
			RtfControls.CreateCommonDocPropsControlWord("ftnrestart"),
			RtfControls.CreateCommonDocPropsControlWord("ftnrstcont"),
			RtfControls.CreateCommonDocPropsControlWord("ftnrstpg"),
			RtfControls.CreateCommonControlWord("ftnsep", 8200U),
			RtfControls.CreateCommonControlWord("ftnsepc", 8200U),
			RtfControls.CreateCommonControlWord("ftnstart", 8196U),
			RtfControls.CreateCommonDocPropsControlWord("ftntj"),
			RtfControls.CreateCommonControlWord("fttruetype", 131074U),
			RtfControls.CreateCommonControlWord("fvaliddos", 2147483650U),
			RtfControls.CreateCommonControlWord("fvalidhpfs", 2147483650U),
			RtfControls.CreateCommonControlWord("fvalidmac", 2147483650U),
			RtfControls.CreateCommonControlWord("fvalidntfs", 2147483650U),
			RtfControls.CreateCommonControlWord("g", 264U),
			RtfControls.CreateCommonControlWord("gcw", 260U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_GREEN, "green", 262148U),
			RtfControls.CreateCommonControlWord("gridtbl", 264U),
			RtfControls.CreateCommonControlWord("gutter", 8196U),
			RtfControls.CreateCommonDocPropsControlWord("gutterprl"),
			RtfControls.CreateCommonControlWord("guttersxn", 4100U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_HEADER, "header", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_HEADERF, "headerf", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_HEADERL, "headerl", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_HEADERR, "headerr", 2147483656U),
			RtfControls.CreateCommonControlWord("headery", 4100U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_HICH, "hich", 130U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_HIGHLIGHT, "highlight", 2147483652U),
			RtfControls.CreateCommonControlWord("hlfr", 2097156U),
			RtfControls.CreateCommonControlWord("hlinkbase", 1073741828U),
			RtfControls.CreateCommonControlWord("hlloc", 2097156U),
			RtfControls.CreateCommonControlWord("hlsrc", 2097156U),
			RtfControls.CreateCommonDocPropsControlWord("horzdoc"),
			RtfControls.CreateCommonControlWord("horzsect", 4098U),
			RtfControls.CreateCommonControlWord("hr", 1073741828U),
			RtfControls.CreateCommonDocPropsControlWord("htmautsp"),
			RtfControls.CreateCommonDocPropsControlWord("htmlbase"),
			RtfControls.CreateCommonControlWord("htmlrtf", 8193U),
			RtfControls.CreateCommonControlWord("htmltag", 8200U),
			RtfControls.CreateCommonControlWord("hyphauto", 8193U),
			RtfControls.CreateCommonControlWord("hyphcaps", 8193U),
			RtfControls.CreateCommonControlWord("hyphconsec", 8196U),
			RtfControls.CreateCommonControlWord("hyphhotz", 8196U),
			RtfControls.CreateCommonControlWord("hyphpar", 513U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_I, "i", 257U),
			RtfControls.CreateCommonControlWord("id", 1073741828U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ILVL, "ilvl", 2147483652U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_IMPR, "impr", 16777473U),
			RtfControls.CreateCommonControlWord("info", 1073741832U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_INTBL, "intbl", 514U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ITAP, "itap", 548U),
			RtfControls.CreateCommonControlWord("ixe", 268435458U),
			RtfControls.CreateCommonDocPropsControlWord("jcompress"),
			RtfControls.CreateCommonDocPropsControlWord("jexpand"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_JPEGBLIP, "jpegblip", 33554434U),
			RtfControls.CreateCommonDocPropsControlWord("jsksu"),
			RtfControls.CreateCommonControlWord("keep", 514U),
			RtfControls.CreateCommonControlWord("keepn", 514U),
			RtfControls.CreateCommonControlWord("kerning", 260U),
			RtfControls.CreateCommonControlWord("keycode", 65544U),
			RtfControls.CreateCommonControlWord("keywords", 1073741832U),
			RtfControls.CreateCommonControlWord("ksulang", 8228U),
			RtfControls.CreateCommonDocPropsControlWord("landscape"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LANG, "lang", 260U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LANGFE, "langfe", 292U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LANGFENP, "langfenp", 292U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LANGNP, "langnp", 292U),
			RtfControls.CreateCommonControlWord("lbr", 48U),
			RtfControls.CreateCommonControlWord("lchars", 8200U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LDBLQUOTE, "ldblquote", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVEL, "level", 516U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELFOLLOW, "levelfollow", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELINDENT, "levelindent", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELJC, "leveljc", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELJCN, "leveljcn", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELLEGAL, "levellegal", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELNFC, "levelnfc", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELNFCN, "levelnfcn", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELNORESTART, "levelnorestart", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELNUMBERS, "levelnumbers", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELOLD, "levelold", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELPREV, "levelprev", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELPREVSPACE, "levelprevspace", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELSPACE, "levelspace", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELSTARTAT, "levelstartat", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELTEMPLATEID, "leveltemplateid", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELTEXT, "leveltext", 2147483652U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LFOLEVEL, "lfolevel", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LI, "li", 516U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LINE, "line", 16U),
			RtfControls.CreateCommonControlWord("linebetcol", 4098U),
			RtfControls.CreateCommonControlWord("linecont", 4098U),
			RtfControls.CreateCommonControlWord("linemod", 4100U),
			RtfControls.CreateCommonControlWord("lineppage", 4098U),
			RtfControls.CreateCommonControlWord("linerestart", 4098U),
			RtfControls.CreateCommonControlWord("linestart", 8196U),
			RtfControls.CreateCommonControlWord("linestarts", 4100U),
			RtfControls.CreateCommonControlWord("linex", 4100U),
			RtfControls.CreateCommonControlWord("linkself", 2147483650U),
			RtfControls.CreateCommonDocPropsControlWord("linkstyles"),
			RtfControls.CreateCommonControlWord("linkval", 1073741828U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LIN, "lin", 548U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISA, "lisa", 548U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISB, "lisb", 548U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LIST, "list", 2147483650U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTHYBRID, "listhybrid", 2147483650U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTID, "listid", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTLEVEL, "listlevel", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTNAME, "listname", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTOVERRIDE, "listoverride", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTOVERRIDECOUNT, "listoverridecount", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTOVERRIDEFORMAT, "listoverrideformat", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTOVERRIDESTART, "listoverridestart", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTPICTURE, "listpicture", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTRESTARTHDN, "listrestarthdn", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTSIMPLE, "listsimple", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTTABLE, "listtable", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTOVERRIDETABLE, "listoverridetable", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTTEMPLATEID, "listtemplateid", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LISTTEXT, "listtext", 2147483656U),
			RtfControls.CreateCommonDocPropsControlWord("lnbrkrule"),
			RtfControls.CreateCommonControlWord("lndscpsxn", 4098U),
			RtfControls.CreateCommonDocPropsControlWord("lnongrid"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LOCH, "loch", 130U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LQUOTE, "lquote", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LS, "ls", 2147483652U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LTRCH, "ltrch", 258U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LTRDOC, "ltrdoc", 8194U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LTRMARK, "ltrmark", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LTRPAR, "ltrpar", 514U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LTRROW, "ltrrow", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_LTRSECT, "ltrsect", 4098U),
			RtfControls.CreateCommonDocPropsControlWord("lytcalctblwd"),
			RtfControls.CreateCommonDocPropsControlWord("lytexcttp"),
			RtfControls.CreateCommonDocPropsControlWord("lytprtmet"),
			RtfControls.CreateCommonDocPropsControlWord("lyttblrtgr"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_MAC, "mac", 2147483650U),
			RtfControls.CreateCommonControlWord("macpict", 33554434U),
			RtfControls.CreateCommonDocPropsControlWord("makebackup"),
			RtfControls.CreateCommonControlWord("manager", 1073741832U),
			RtfControls.CreateCommonControlWord("margb", 8196U),
			RtfControls.CreateCommonControlWord("margbsxn", 4100U),
			RtfControls.CreateCommonControlWord("margl", 8196U),
			RtfControls.CreateCommonControlWord("marglsxn", 4100U),
			RtfControls.CreateCommonDocPropsControlWord("margmirror"),
			RtfControls.CreateCommonControlWord("margr", 8196U),
			RtfControls.CreateCommonControlWord("margrsxn", 4100U),
			RtfControls.CreateCommonControlWord("margt", 8196U),
			RtfControls.CreateCommonControlWord("margtsxn", 4100U),
			RtfControls.CreateCommonControlWord("mhtmltag", 8U),
			RtfControls.CreateCommonControlWord("min", 1073741828U),
			RtfControls.CreateCommonControlWord("mo", 1073741828U),
			RtfControls.CreateCommonDocPropsControlWord("msmcap"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_NESTCELL, "nestcell", 1048592U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_NESTROW, "nestrow", 1048592U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_NESTTABLEPROPS, "nesttableprops", 1048584U),
			RtfControls.CreateCommonControlWord("nextfile", 8200U),
			RtfControls.CreateCommonDocPropsControlWord("nocolbal"),
			RtfControls.CreateCommonControlWord("nocwrap", 514U),
			RtfControls.CreateCommonDocPropsControlWord("noextrasprl"),
			RtfControls.CreateCommonControlWord("nofchars", 1073741828U),
			RtfControls.CreateCommonControlWord("nofcharsws", 1073741828U),
			RtfControls.CreateCommonControlWord("nofpages", 1073741828U),
			RtfControls.CreateCommonControlWord("nofwords", 1073741828U),
			RtfControls.CreateCommonDocPropsControlWord("nolead"),
			RtfControls.CreateCommonControlWord("noline", 514U),
			RtfControls.CreateCommonDocPropsControlWord("nolnhtadjtbl"),
			RtfControls.CreateCommonControlWord("nonesttables", 1048584U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_NONSHPPICT, "nonshppict", 33554434U),
			RtfControls.CreateCommonControlWord("nooverflow", 514U),
			RtfControls.CreateCommonControlWord("noproof", 258U),
			RtfControls.CreateCommonControlWord("nosectexpand", 258U),
			RtfControls.CreateCommonControlWord("nosnaplinegrid", 514U),
			RtfControls.CreateCommonDocPropsControlWord("nospaceforul"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_NOSUPERSUB, "nosupersub", 258U),
			RtfControls.CreateCommonDocPropsControlWord("notabind"),
			RtfControls.CreateCommonDocPropsControlWord("noultrlspc"),
			RtfControls.CreateCommonControlWord("nowidctlpar", 514U),
			RtfControls.CreateCommonControlWord("nowrap", 4194306U),
			RtfControls.CreateCommonControlWord("nowwrap", 514U),
			RtfControls.CreateCommonDocPropsControlWord("noxlattoyen"),
			RtfControls.CreateCommonControlWord("objalias", 2147483656U),
			RtfControls.CreateCommonControlWord("objalign", 2147483652U),
			RtfControls.CreateCommonControlWord("objattph", 2147483650U),
			RtfControls.CreateCommonControlWord("objautlink", 2147483650U),
			RtfControls.CreateCommonControlWord("objclass", 2147483656U),
			RtfControls.CreateCommonControlWord("objcropb", 2147483652U),
			RtfControls.CreateCommonControlWord("objcropl", 2147483652U),
			RtfControls.CreateCommonControlWord("objcropr", 2147483652U),
			RtfControls.CreateCommonControlWord("objcropt", 2147483652U),
			RtfControls.CreateCommonControlWord("objdata", 2147483656U),
			RtfControls.CreateCommonControlWord("object", 2147483656U),
			RtfControls.CreateCommonControlWord("objemb", 2147483650U),
			RtfControls.CreateCommonControlWord("objh", 2147483652U),
			RtfControls.CreateCommonControlWord("objhtml", 2147483650U),
			RtfControls.CreateCommonControlWord("objicemb", 2147483650U),
			RtfControls.CreateCommonControlWord("objlink", 2147483650U),
			RtfControls.CreateCommonControlWord("objlock", 2147483650U),
			RtfControls.CreateCommonControlWord("objname", 2147483656U),
			RtfControls.CreateCommonControlWord("objocx", 2147483650U),
			RtfControls.CreateCommonControlWord("objpub", 2147483650U),
			RtfControls.CreateCommonControlWord("objscalex", 2147483652U),
			RtfControls.CreateCommonControlWord("objscaley", 2147483652U),
			RtfControls.CreateCommonControlWord("objsect", 2147483656U),
			RtfControls.CreateCommonControlWord("objsetsize", 2147483650U),
			RtfControls.CreateCommonControlWord("objsub", 2147483650U),
			RtfControls.CreateCommonControlWord("objtime", 2147483656U),
			RtfControls.CreateCommonControlWord("objtransy", 2147483652U),
			RtfControls.CreateCommonControlWord("objupdate", 2147483650U),
			RtfControls.CreateCommonControlWord("objw", 2147483652U),
			RtfControls.CreateCommonDocPropsControlWord("oldas"),
			RtfControls.CreateCommonDocPropsControlWord("oldlinewrap"),
			RtfControls.CreateCommonControlWord("operator", 1073741832U),
			RtfControls.CreateCommonDocPropsControlWord("otblrul"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_OUTL, "outl", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_OUTLINELEVEL, "outlinelevel", 2147483684U),
			RtfControls.CreateCommonControlWord("overlay", 578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PAGE, "page", 16U),
			RtfControls.CreateCommonControlWord("pagebb", 514U),
			RtfControls.CreateCommonControlWord("panose", 131080U),
			RtfControls.CreateCommonControlWord("paperh", 8196U),
			RtfControls.CreateCommonControlWord("paperw", 8196U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PAR, "par", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PARD, "pard", 514U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PC, "pc", 2147483650U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PCA, "pca", 2147483650U),
			RtfControls.CreateCommonDocPropsControlWord("pgbrdrb"),
			RtfControls.CreateCommonDocPropsControlWord("pgbrdrfoot"),
			RtfControls.CreateCommonDocPropsControlWord("pgbrdrhead"),
			RtfControls.CreateCommonDocPropsControlWord("pgbrdrl"),
			RtfControls.CreateCommonControlWord("pgbrdropt", 8228U),
			RtfControls.CreateCommonDocPropsControlWord("pgbrdrr"),
			RtfControls.CreateCommonDocPropsControlWord("pgbrdrsnap"),
			RtfControls.CreateCommonDocPropsControlWord("pgbrdrt"),
			RtfControls.CreateCommonControlWord("pghsxn", 4100U),
			RtfControls.CreateCommonControlWord("pgnbidia", 4098U),
			RtfControls.CreateCommonControlWord("pgnbidib", 4098U),
			RtfControls.CreateCommonControlWord("pgnchosung", 524290U),
			RtfControls.CreateCommonControlWord("pgncnum", 524290U),
			RtfControls.CreateCommonControlWord("pgncont", 4098U),
			RtfControls.CreateCommonControlWord("pgndbnum", 4098U),
			RtfControls.CreateCommonControlWord("pgndbnumd", 4098U),
			RtfControls.CreateCommonControlWord("pgndbnumk", 524290U),
			RtfControls.CreateCommonControlWord("pgndbnumt", 524290U),
			RtfControls.CreateCommonControlWord("pgndec", 4098U),
			RtfControls.CreateCommonControlWord("pgndecd", 4098U),
			RtfControls.CreateCommonControlWord("pgnganada", 524290U),
			RtfControls.CreateCommonControlWord("pgngbnum", 524290U),
			RtfControls.CreateCommonControlWord("pgngbnumd", 524290U),
			RtfControls.CreateCommonControlWord("pgngbnumk", 524290U),
			RtfControls.CreateCommonControlWord("pgngbnuml", 524290U),
			RtfControls.CreateCommonControlWord("pgnhn", 4100U),
			RtfControls.CreateCommonControlWord("pgnhnsc", 4098U),
			RtfControls.CreateCommonControlWord("pgnhnsh", 4098U),
			RtfControls.CreateCommonControlWord("pgnhnsm", 4098U),
			RtfControls.CreateCommonControlWord("pgnhnsn", 4098U),
			RtfControls.CreateCommonControlWord("pgnhnsp", 4098U),
			RtfControls.CreateCommonControlWord("pgnlcltr", 4098U),
			RtfControls.CreateCommonControlWord("pgnlcrm", 4098U),
			RtfControls.CreateCommonControlWord("pgnrestart", 4098U),
			RtfControls.CreateCommonControlWord("pgnstart", 8196U),
			RtfControls.CreateCommonControlWord("pgnstarts", 4100U),
			RtfControls.CreateCommonControlWord("pgnucltr", 4098U),
			RtfControls.CreateCommonControlWord("pgnucrm", 4098U),
			RtfControls.CreateCommonControlWord("pgnx", 4100U),
			RtfControls.CreateCommonControlWord("pgny", 4100U),
			RtfControls.CreateCommonControlWord("pgnzodiac", 524290U),
			RtfControls.CreateCommonControlWord("pgnzodiacd", 524290U),
			RtfControls.CreateCommonControlWord("pgnzodiacl", 524290U),
			RtfControls.CreateCommonControlWord("pgwsxn", 4100U),
			RtfControls.CreateCommonControlWord("phcol", 4194306U),
			RtfControls.CreateCommonControlWord("phmrg", 4194306U),
			RtfControls.CreateCommonControlWord("phpg", 4194306U),
			RtfControls.CreateCommonControlWord("picbmp", 33554434U),
			RtfControls.CreateCommonControlWord("picbpp", 2147483652U),
			RtfControls.CreateCommonControlWord("piccropb", 2147483652U),
			RtfControls.CreateCommonControlWord("piccropl", 2147483652U),
			RtfControls.CreateCommonControlWord("piccropr", 2147483652U),
			RtfControls.CreateCommonControlWord("piccropt", 2147483652U),
			RtfControls.CreateCommonControlWord("pich", 2147483652U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PICHGOAL, "pichgoal", 2147483652U),
			RtfControls.CreateCommonControlWord("picprop", 33554440U),
			RtfControls.CreateCommonControlWord("picscaled", 33554434U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PICSCALEX, "picscalex", 2147483652U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PICSCALEY, "picscaley", 2147483652U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PICT, "pict", 33554440U),
			RtfControls.CreateCommonControlWord("picw", 2147483652U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PICWGOAL, "picwgoal", 2147483652U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PLAIN, "plain", 258U),
			RtfControls.CreateCommonControlWord("pmmetafile", 2147483652U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PN, "pn", 524296U),
			RtfControls.CreateCommonControlWord("pnacross", 524290U),
			RtfControls.CreateCommonControlWord("pnaiu", 524290U),
			RtfControls.CreateCommonControlWord("pnaiud", 524290U),
			RtfControls.CreateCommonControlWord("pnaiueo", 524290U),
			RtfControls.CreateCommonControlWord("pnaiueod", 524290U),
			RtfControls.CreateCommonControlWord("pnb", 524289U),
			RtfControls.CreateCommonControlWord("pnbidia", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNBIDIB, "pnbidib", 524290U),
			RtfControls.CreateCommonControlWord("pncaps", 524289U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNCARD, "pncard", 524290U),
			RtfControls.CreateCommonControlWord("pncf", 524292U),
			RtfControls.CreateCommonControlWord("pnchosung", 524290U),
			RtfControls.CreateCommonControlWord("pncnum", 524290U),
			RtfControls.CreateCommonControlWord("pndbnum", 524290U),
			RtfControls.CreateCommonControlWord("pndbnumd", 524290U),
			RtfControls.CreateCommonControlWord("pndbnumk", 524290U),
			RtfControls.CreateCommonControlWord("pndbnuml", 524290U),
			RtfControls.CreateCommonControlWord("pndbnumt", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNDEC, "pndec", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNDECD, "pndecd", 524290U),
			RtfControls.CreateCommonControlWord("pnf", 524292U),
			RtfControls.CreateCommonControlWord("pnfs", 524292U),
			RtfControls.CreateCommonControlWord("pnganada", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNGBLIP, "pngblip", 33554434U),
			RtfControls.CreateCommonControlWord("pngbnum", 524290U),
			RtfControls.CreateCommonControlWord("pngbnumd", 524290U),
			RtfControls.CreateCommonControlWord("pngbnumk", 524290U),
			RtfControls.CreateCommonControlWord("pngbnuml", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNHANG, "pnhang", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNI, "pni", 524289U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNINDENT, "pnindent", 524292U),
			RtfControls.CreateCommonControlWord("pniroha", 524290U),
			RtfControls.CreateCommonControlWord("pnirohad", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNLCLTR, "pnlcltr", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNLCRM, "pnlcrm", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNLVL, "pnlvl", 524292U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNLVLBLT, "pnlvlblt", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNLVLBODY, "pnlvlbody", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNLVLCONT, "pnlvlcont", 524290U),
			RtfControls.CreateCommonControlWord("pnnumonce", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNORD, "pnord", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNORDT, "pnordt", 524290U),
			RtfControls.CreateCommonControlWord("pnprev", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNQC, "pnqc", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNQL, "pnql", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNQR, "pnqr", 524290U),
			RtfControls.CreateCommonControlWord("pnrauth", 2147483684U),
			RtfControls.CreateCommonControlWord("pnrdate", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNRESTART, "pnrestart", 524290U),
			RtfControls.CreateCommonControlWord("pnrnfc", 2147483684U),
			RtfControls.CreateCommonControlWord("pnrnot", 578U),
			RtfControls.CreateCommonControlWord("pnrpnbr", 2147483684U),
			RtfControls.CreateCommonControlWord("pnrrgb", 2147483684U),
			RtfControls.CreateCommonControlWord("pnrstart", 2147483684U),
			RtfControls.CreateCommonControlWord("pnrstop", 2147483684U),
			RtfControls.CreateCommonControlWord("pnrxst", 2147483684U),
			RtfControls.CreateCommonControlWord("pnscaps", 524289U),
			RtfControls.CreateCommonControlWord("pnseclvl", 524296U),
			RtfControls.CreateCommonControlWord("pnsp", 524292U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNSTART, "pnstart", 524292U),
			RtfControls.CreateCommonControlWord("pnstrike", 524289U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNTEXT, "pntext", 524296U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNTXTA, "pntxta", 524296U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNTXTB, "pntxtb", 524296U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNUCLTR, "pnucltr", 524290U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_PNUCRM, "pnucrm", 524290U),
			RtfControls.CreateCommonControlWord("pnul", 524289U),
			RtfControls.CreateCommonControlWord("pnuld", 524290U),
			RtfControls.CreateCommonControlWord("pnuldash", 524290U),
			RtfControls.CreateCommonControlWord("pnuldashd", 524290U),
			RtfControls.CreateCommonControlWord("pnuldashdd", 524290U),
			RtfControls.CreateCommonControlWord("pnuldb", 524290U),
			RtfControls.CreateCommonControlWord("pnulhair", 524290U),
			RtfControls.CreateCommonControlWord("pnulnone", 524290U),
			RtfControls.CreateCommonControlWord("pnulth", 524290U),
			RtfControls.CreateCommonControlWord("pnulw", 524290U),
			RtfControls.CreateCommonControlWord("pnulwave", 524290U),
			RtfControls.CreateCommonControlWord("pnzodiac", 524290U),
			RtfControls.CreateCommonControlWord("pnzodiacd", 524290U),
			RtfControls.CreateCommonControlWord("pnzodiacl", 524290U),
			RtfControls.CreateCommonControlWord("posnegx", 4194308U),
			RtfControls.CreateCommonControlWord("posnegy", 4194308U),
			RtfControls.CreateCommonControlWord("posx", 4194308U),
			RtfControls.CreateCommonControlWord("posxc", 4194306U),
			RtfControls.CreateCommonControlWord("posxi", 4194306U),
			RtfControls.CreateCommonControlWord("posxl", 4194306U),
			RtfControls.CreateCommonControlWord("posxo", 4194306U),
			RtfControls.CreateCommonControlWord("posxr", 4194306U),
			RtfControls.CreateCommonControlWord("posy", 4194308U),
			RtfControls.CreateCommonControlWord("posyb", 4194306U),
			RtfControls.CreateCommonControlWord("posyc", 4194306U),
			RtfControls.CreateCommonControlWord("posyil", 4194306U),
			RtfControls.CreateCommonControlWord("posyin", 578U),
			RtfControls.CreateCommonControlWord("posyout", 578U),
			RtfControls.CreateCommonControlWord("posyt", 4194306U),
			RtfControls.CreateCommonDocPropsControlWord("prcolbl"),
			RtfControls.CreateCommonDocPropsControlWord("printdata"),
			RtfControls.CreateCommonControlWord("printim", 1073741832U),
			RtfControls.CreateCommonControlWord("private", 8200U),
			RtfControls.CreateCommonControlWord("propname", 1073741828U),
			RtfControls.CreateCommonControlWord("proptype", 1073741828U),
			RtfControls.CreateCommonDocPropsControlWord("psover"),
			RtfControls.CreateCommonControlWord("psz", 8196U),
			RtfControls.CreateCommonControlWord("pubauto", 1026U),
			RtfControls.CreateCommonControlWord("pvmrg", 4194306U),
			RtfControls.CreateCommonControlWord("pvpara", 4194306U),
			RtfControls.CreateCommonControlWord("pvpg", 4194306U),
			RtfControls.CreateCommonControlWord("pwd", 40U),
			RtfControls.CreateCommonControlWord("pxe", 268435464U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_QC, "qc", 514U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_QD, "qd", 514U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_QJ, "qj", 514U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_QL, "ql", 514U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_QMSPACE, "qmspace", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_QR, "qr", 514U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_RDBLQUOTE, "rdblquote", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_RED, "red", 262148U),
			RtfControls.CreateCommonControlWord("result", 2147483656U),
			RtfControls.CreateCommonControlWord("revauth", 260U),
			RtfControls.CreateCommonControlWord("revauthdel", 16777508U),
			RtfControls.CreateCommonControlWord("revbar", 8196U),
			RtfControls.CreateCommonControlWord("revdttm", 260U),
			RtfControls.CreateCommonControlWord("revdttmdel", 16777508U),
			RtfControls.CreateCommonControlWord("revised", 257U),
			RtfControls.CreateCommonDocPropsControlWord("revisions"),
			RtfControls.CreateCommonControlWord("revprop", 8196U),
			RtfControls.CreateCommonDocPropsControlWord("revprot"),
			RtfControls.CreateCommonControlWord("revtbl", 8U),
			RtfControls.CreateCommonControlWord("revtim", 1073741832U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_RI, "ri", 516U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_RIN, "rin", 548U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ROW, "row", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_RQUOTE, "rquote", 16U),
			RtfControls.CreateCommonControlWord("rsltbmp", 2147483650U),
			RtfControls.CreateCommonControlWord("rslthtml", 2147483650U),
			RtfControls.CreateCommonControlWord("rsltmerge", 2147483650U),
			RtfControls.CreateCommonControlWord("rsltpict", 2147483650U),
			RtfControls.CreateCommonControlWord("rsltrtf", 2147483650U),
			RtfControls.CreateCommonControlWord("rslttxt", 2147483650U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_RTF, "rtf", 16384U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_RTLCH, "rtlch", 258U),
			RtfControls.CreateCommonDocPropsControlWord("rtldoc"),
			RtfControls.CreateCommonDocPropsControlWord("rtlgutter"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_RTLMARK, "rtlmark", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_RTLPAR, "rtlpar", 514U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_RTLROW, "rtlrow", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_RTLSECT, "rtlsect", 4098U),
			RtfControls.CreateCommonControlWord("rxe", 268435464U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_S, "s", 516U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SA, "sa", 516U),
			RtfControls.CreateCommonControlWord("saauto", 545U),
			RtfControls.CreateCommonControlWord("sautoupd", 65538U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SB, "sb", 516U),
			RtfControls.CreateCommonControlWord("sbasedon", 65540U),
			RtfControls.CreateCommonControlWord("sbauto", 545U),
			RtfControls.CreateCommonControlWord("sbkcol", 4098U),
			RtfControls.CreateCommonControlWord("sbkeven", 4098U),
			RtfControls.CreateCommonControlWord("sbknone", 4098U),
			RtfControls.CreateCommonControlWord("sbkodd", 4098U),
			RtfControls.CreateCommonControlWord("sbkpage", 4098U),
			RtfControls.CreateCommonControlWord("sbys", 514U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SCAPS, "scaps", 257U),
			RtfControls.CreateCommonControlWord("scompose", 65538U),
			RtfControls.CreateCommonControlWord("sec", 1073741828U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SECT, "sect", 16U),
			RtfControls.CreateCommonControlWord("sectd", 4098U),
			RtfControls.CreateCommonControlWord("sectdefaultcl", 4100U),
			RtfControls.CreateCommonControlWord("sectexpand", 4132U),
			RtfControls.CreateCommonControlWord("sectlinegrid", 4132U),
			RtfControls.CreateCommonControlWord("sectnum", 16U),
			RtfControls.CreateCommonControlWord("sectspecifycl", 4100U),
			RtfControls.CreateCommonControlWord("sectspecifygen", 4130U),
			RtfControls.CreateCommonControlWord("sectspecifyl", 4100U),
			RtfControls.CreateCommonControlWord("sectunlocked", 4098U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SHAD, "shad", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SHADING, "shading", 16777732U),
			RtfControls.CreateCommonControlWord("shidden", 65538U),
			RtfControls.CreateCommonControlWord("shift", 65538U),
			RtfControls.CreateCommonControlWord("shpbottom", 2097188U),
			RtfControls.CreateCommonControlWord("shpbxcolumn", 2097154U),
			RtfControls.CreateCommonControlWord("shpbxignore", 2097154U),
			RtfControls.CreateCommonControlWord("shpbxmargin", 2097154U),
			RtfControls.CreateCommonControlWord("shpbxpage", 2097154U),
			RtfControls.CreateCommonControlWord("shpbyignore", 2097154U),
			RtfControls.CreateCommonControlWord("shpbymargin", 2097154U),
			RtfControls.CreateCommonControlWord("shpbypage", 2097154U),
			RtfControls.CreateCommonControlWord("shpbypara", 2097154U),
			RtfControls.CreateCommonControlWord("shpfblwtxt", 2097188U),
			RtfControls.CreateCommonControlWord("shpfhdr", 2097188U),
			RtfControls.CreateCommonControlWord("shpgrp", 2097156U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SHPINST, "shpinst", 2097160U),
			RtfControls.CreateCommonControlWord("shpleft", 2097188U),
			RtfControls.CreateCommonControlWord("shplid", 2097188U),
			RtfControls.CreateCommonControlWord("shplockanchor", 2097154U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SHPPICT, "shppict", 33554440U),
			RtfControls.CreateCommonControlWord("shpright", 2097188U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SHPRSLT, "shprslt", 2097156U),
			RtfControls.CreateCommonControlWord("shptop", 2097188U),
			RtfControls.CreateCommonControlWord("shptxt", 2097156U),
			RtfControls.CreateCommonControlWord("shpwrk", 2097188U),
			RtfControls.CreateCommonControlWord("shpwr", 2097188U),
			RtfControls.CreateCommonControlWord("shpz", 2097188U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SL, "sl", 516U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SLMULT, "slmult", 516U),
			RtfControls.CreateCommonControlWord("snext", 65540U),
			RtfControls.CreateCommonControlWord("softcol", 2147483650U),
			RtfControls.CreateCommonControlWord("softlheight", 2147483652U),
			RtfControls.CreateCommonControlWord("softline", 2147483650U),
			RtfControls.CreateCommonControlWord("softpage", 2147483650U),
			RtfControls.CreateCommonControlWord("spersonal", 65538U),
			RtfControls.CreateCommonDocPropsControlWord("splytwnine"),
			RtfControls.CreateCommonDocPropsControlWord("sprsbsp"),
			RtfControls.CreateCommonDocPropsControlWord("sprslnsp"),
			RtfControls.CreateCommonDocPropsControlWord("sprsspbf"),
			RtfControls.CreateCommonDocPropsControlWord("sprstsm"),
			RtfControls.CreateCommonDocPropsControlWord("sprstsp"),
			RtfControls.CreateCommonControlWord("sreply", 65538U),
			RtfControls.CreateCommonControlWord("staticval", 1073741828U),
			RtfControls.CreateCommonControlWord("stextflow", 2147483652U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_STRIKE, "strike", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_STRIKED, "striked", 16777473U),
			RtfControls.CreateCommonControlWord("stylesheet", 65544U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SUB, "sub", 258U),
			RtfControls.CreateCommonControlWord("subdocument", 516U),
			RtfControls.CreateCommonDocPropsControlWord("subfontbysize"),
			RtfControls.CreateCommonControlWord("subject", 1073741832U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_SUPER, "super", 258U),
			RtfControls.CreateCommonDocPropsControlWord("swpbdr"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TAB, "tab", 16U),
			RtfControls.CreateCommonControlWord("tabsnoovrlp", 1048578U),
			RtfControls.CreateCommonControlWord("taprtl", 1048578U),
			RtfControls.CreateCommonControlWord("tb", 2147483652U),
			RtfControls.CreateCommonControlWord("tc", 2147483656U),
			RtfControls.CreateCommonControlWord("tcelld", 1048578U),
			RtfControls.CreateCommonControlWord("tcf", 2147483652U),
			RtfControls.CreateCommonControlWord("tcl", 2147483652U),
			RtfControls.CreateCommonControlWord("tcn", 2147483650U),
			RtfControls.CreateCommonControlWord("tdfrmtxtbottom", 1048612U),
			RtfControls.CreateCommonControlWord("tdfrmtxtleft", 1048612U),
			RtfControls.CreateCommonControlWord("tdfrmtxtright", 1048612U),
			RtfControls.CreateCommonControlWord("tdfrmtxttop", 1048612U),
			RtfControls.CreateCommonControlWord("template", 8200U),
			RtfControls.CreateCommonControlWord("time", 67108866U),
			RtfControls.CreateCommonControlWord("title", 1073741832U),
			RtfControls.CreateCommonControlWord("titlepg", 4098U),
			RtfControls.CreateCommonControlWord("tldot", 2147483650U),
			RtfControls.CreateCommonControlWord("tleq", 2147483650U),
			RtfControls.CreateCommonControlWord("tlhyph", 2147483650U),
			RtfControls.CreateCommonControlWord("tlmdot", 2147483650U),
			RtfControls.CreateCommonControlWord("tlth", 2147483650U),
			RtfControls.CreateCommonControlWord("tlul", 2147483650U),
			RtfControls.CreateCommonControlWord("tphcol", 1048578U),
			RtfControls.CreateCommonControlWord("tphmrg", 1048578U),
			RtfControls.CreateCommonControlWord("tphpg", 1048578U),
			RtfControls.CreateCommonControlWord("tposnegx", 1048612U),
			RtfControls.CreateCommonControlWord("tposnegy", 1048612U),
			RtfControls.CreateCommonControlWord("tposxc", 1048578U),
			RtfControls.CreateCommonControlWord("tposxi", 1048578U),
			RtfControls.CreateCommonControlWord("tposxl", 1048578U),
			RtfControls.CreateCommonControlWord("tposx", 1048612U),
			RtfControls.CreateCommonControlWord("tposxo", 1048578U),
			RtfControls.CreateCommonControlWord("tposxr", 1048578U),
			RtfControls.CreateCommonControlWord("tposy", 1048578U),
			RtfControls.CreateCommonControlWord("tposyb", 1048578U),
			RtfControls.CreateCommonControlWord("tposyc", 1048578U),
			RtfControls.CreateCommonControlWord("tposyil", 1048578U),
			RtfControls.CreateCommonControlWord("tposyin", 1048578U),
			RtfControls.CreateCommonControlWord("tposyoutv", 1048578U),
			RtfControls.CreateCommonControlWord("tposyt", 1048578U),
			RtfControls.CreateCommonControlWord("tpvmrg", 1048578U),
			RtfControls.CreateCommonControlWord("tpvpara", 1048578U),
			RtfControls.CreateCommonControlWord("tpvpg", 1048578U),
			RtfControls.CreateCommonControlWord("tqc", 2147483650U),
			RtfControls.CreateCommonControlWord("tqdec", 2147483650U),
			RtfControls.CreateCommonControlWord("tqr", 2147483650U),
			RtfControls.CreateCommonDocPropsControlWord("transmf"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRAUTOFIT, "trautofit", 1048609U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRBRDRB, "trbrdrb", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRBRDRH, "trbrdrh", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRBRDRL, "trbrdrl", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRBRDRR, "trbrdrr", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRBRDRT, "trbrdrt", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRBRDRV, "trbrdrv", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRFTSWIDTHA, "trftswidtha", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRFTSWIDTHB, "trftswidthb", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRFTSWIDTH, "trftswidth", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRGAPH, "trgaph", 1048580U),
			RtfControls.CreateCommonControlWord("trhdr", 1048578U),
			RtfControls.CreateCommonControlWord("trkeep", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRLEFT, "trleft", 1048580U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TROWD, "trowd", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDB, "trpaddb", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDFB, "trpaddfb", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDFL, "trpaddfl", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDFR, "trpaddfr", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDFT, "trpaddft", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDL, "trpaddl", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDR, "trpaddr", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDT, "trpaddt", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRQC, "trqc", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRQL, "trql", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRQR, "trqr", 1048578U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRRH, "trrh", 1048580U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDB, "trspdb", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDFB, "trspdfb", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDFL, "trspdfl", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDFR, "trspdfr", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDFT, "trspdft", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDL, "trspdl", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDR, "trspdr", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDT, "trspdt", 1048612U),
			RtfControls.CreateCommonDocPropsControlWord("truncatefontheight"),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRWWIDTHA, "trwwidtha", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRWWIDTHB, "trwwidthb", 1048612U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_TRWWIDTH, "trwwidth", 1048612U),
			RtfControls.CreateCommonDocPropsControlWord("twoonone"),
			RtfControls.CreateCommonControlWord("tx", 2147483652U),
			RtfControls.CreateCommonControlWord("txe", 268435464U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_UC, "uc", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_UD, "ud", 2147483656U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_UL, "ul", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULC, "ulc", 292U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULD, "uld", 258U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULDASH, "uldash", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULDASHD, "uldashd", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULDASHDD, "uldashdd", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULDB, "uldb", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULHAIR, "ulhair", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULHWAVE, "ulhwave", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULLDASH, "ulldash", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULNONE, "ulnone", 258U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULTH, "ulth", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULTHD, "ulthd", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULTHDASH, "ulthdash", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULTHDASHD, "ulthdashd", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULTHDASHDD, "ulthdashdd", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULTHLDASH, "ulthldash", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULULDBWAVE, "ululdbwave", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULW, "ulw", 258U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ULWAVE, "ulwave", 257U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_U, "u", 2147483684U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_UP, "up", 260U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_UPR, "upr", 2147483656U),
			RtfControls.CreateCommonControlWord("urtf", 40U),
			RtfControls.CreateCommonDocPropsControlWord("useltbaln"),
			RtfControls.CreateCommonControlWord("userprops", 1073741832U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_V, "v", 257U),
			RtfControls.CreateCommonControlWord("vern", 1073741828U),
			RtfControls.CreateCommonControlWord("version", 1073741828U),
			RtfControls.CreateCommonControlWord("vertalb", 4098U),
			RtfControls.CreateCommonControlWord("vertalc", 4098U),
			RtfControls.CreateCommonControlWord("vertalj", 4098U),
			RtfControls.CreateCommonControlWord("vertalt", 4098U),
			RtfControls.CreateCommonDocPropsControlWord("vertdoc"),
			RtfControls.CreateCommonControlWord("vertsect", 4098U),
			RtfControls.CreateCommonControlWord("viewkind", 8228U),
			RtfControls.CreateCommonControlWord("viewscale", 8228U),
			RtfControls.CreateCommonControlWord("viewzk", 8228U),
			RtfControls.CreateCommonControlWord("wbitmap", 2147483652U),
			RtfControls.CreateCommonControlWord("wbmbitspixel", 2147483652U),
			RtfControls.CreateCommonControlWord("wbmplanes", 2147483652U),
			RtfControls.CreateCommonControlWord("wbmwidthbytes", 2147483652U),
			RtfControls.CreateCommonControlWord("webhidden", 258U),
			RtfControls.CreateCommonControlWord("widctlpar", 514U),
			RtfControls.CreateCommonDocPropsControlWord("widowctrl"),
			RtfControls.CreateCommonControlWord("windowcaption", 8196U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_WMETAFILE, "wmetafile", 2147483652U),
			RtfControls.CreateCommonControlWord("wpeqn", 67108866U),
			RtfControls.CreateCommonDocPropsControlWord("wpjst"),
			RtfControls.CreateCommonDocPropsControlWord("wpsp"),
			RtfControls.CreateCommonDocPropsControlWord("wraptrsp"),
			RtfControls.CreateCommonControlWord("xe", 268435464U),
			RtfControls.CreateCommonControlWord("xef", 268435460U),
			RtfControls.CreateCommonControlWord("yr", 1073741828U),
			RtfControls.CreateCommonControlWord("yxe", 268435458U),
			RtfControls.CreateCommonControlWord("zwbo", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ZWJ, "zwj", 16U),
			RtfControls.CreateCommonControlWord("zwnbo", 16U),
			new RtfControlWordInfo(RtfControlWord.Ctrl_ZWNJ, "zwnj", 16U)
		};
	}
}
