using System;

namespace System.Windows.Controls.Primitives
{
	/// <summary>Describes the behavior that caused a <see cref="E:System.Windows.Controls.Primitives.ScrollBar.Scroll" /> event for a <see cref="T:System.Windows.Controls.Primitives.ScrollBar" /> control. </summary>
	// Token: 0x020005A5 RID: 1445
	public enum ScrollEventType
	{
		/// <summary>The <see cref="T:System.Windows.Controls.Primitives.Thumb" /> was dragged to a new position and is now no longer being dragged by the user.</summary>
		// Token: 0x040030C9 RID: 12489
		EndScroll,
		/// <summary>The <see cref="T:System.Windows.Controls.Primitives.Thumb" /> moved to the <see cref="P:System.Windows.Controls.Primitives.RangeBase.Minimum" /> position of the <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />. For a vertical <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />, this movement occurs when the CTRL+HOME keys are pressed. This movement corresponds to a <see cref="F:System.Windows.Controls.Primitives.ScrollBar.ScrollToTopCommand" /> in a vertical <see cref="T:System.Windows.Controls.Primitives.ScrollBar" /> and a <see cref="F:System.Windows.Controls.Primitives.ScrollBar.ScrollToLeftEndCommand" /> in a horizontal <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />.</summary>
		// Token: 0x040030CA RID: 12490
		First,
		/// <summary>The <see cref="T:System.Windows.Controls.Primitives.Thumb" /> moved a specified distance, as determined by the value of <see cref="P:System.Windows.Controls.Primitives.RangeBase.LargeChange" />, to the left for a horizontal <see cref="T:System.Windows.Controls.Primitives.ScrollBar" /> or upward for a vertical <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />. For a vertical <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />, this movement occurs when the page button that is above the <see cref="T:System.Windows.Controls.Primitives.Thumb" /> is pressed, or when the PAGE UP key is pressed, and corresponds to a <see cref="F:System.Windows.Controls.Primitives.ScrollBar.PageUpCommand" />. For a horizontal <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />, this movement occurs when the page button to the left of the <see cref="T:System.Windows.Controls.Primitives.Thumb" /> is pressed, and corresponds to a <see cref="F:System.Windows.Controls.Primitives.ScrollBar.PageLeftCommand" />.</summary>
		// Token: 0x040030CB RID: 12491
		LargeDecrement,
		/// <summary>The <see cref="T:System.Windows.Controls.Primitives.Thumb" /> moved a specified distance, as determined by the value of <see cref="P:System.Windows.Controls.Primitives.RangeBase.LargeChange" />, to the right for a horizontal <see cref="T:System.Windows.Controls.Primitives.ScrollBar" /> or downward for a vertical <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />. For a vertical <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />, this movement occurs when the page button that is below the <see cref="T:System.Windows.Controls.Primitives.Thumb" /> is pressed, or when the PAGE DOWN key is pressed, and corresponds to a <see cref="F:System.Windows.Controls.Primitives.ScrollBar.PageDownCommand" />. For a horizontal <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />, this movement occurs when the page button to the right of the <see cref="T:System.Windows.Controls.Primitives.Thumb" /> is pressed, and corresponds to a <see cref="F:System.Windows.Controls.Primitives.ScrollBar.PageRightCommand" />.</summary>
		// Token: 0x040030CC RID: 12492
		LargeIncrement,
		/// <summary>The <see cref="T:System.Windows.Controls.Primitives.Thumb" /> moved to the <see cref="P:System.Windows.Controls.Primitives.RangeBase.Maximum" /> position of the <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />. For a vertical <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />, this movement occurs when the CTRL+END keys are pressed. This movement corresponds to a <see cref="F:System.Windows.Controls.Primitives.ScrollBar.ScrollToEndCommand" /> in a vertical <see cref="T:System.Windows.Controls.Primitives.ScrollBar" /> and a <see cref="F:System.Windows.Controls.Primitives.ScrollBar.ScrollToRightEndCommand" /> in a horizontal <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />.</summary>
		// Token: 0x040030CD RID: 12493
		Last,
		/// <summary>The <see cref="T:System.Windows.Controls.Primitives.Thumb" /> moved a small distance, as determined by the value of <see cref="P:System.Windows.Controls.Primitives.RangeBase.SmallChange" />, to the left for a horizontal <see cref="T:System.Windows.Controls.Primitives.ScrollBar" /> or upward for a vertical <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />. For a vertical <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />, this movement occurs when the upper <see cref="T:System.Windows.Controls.Primitives.RepeatButton" /> is pressed or when the UP ARROW key is pressed, and corresponds to a <see cref="F:System.Windows.Controls.Primitives.ScrollBar.LineUpCommand" />. For a horizontal <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />, this movement occurs when the left <see cref="T:System.Windows.Controls.Primitives.RepeatButton" /> is pressed, and corresponds to a <see cref="F:System.Windows.Controls.Primitives.ScrollBar.LineLeftCommand" />.</summary>
		// Token: 0x040030CE RID: 12494
		SmallDecrement,
		/// <summary>The <see cref="T:System.Windows.Controls.Primitives.Thumb" /> moved a small distance, as determined by the value of <see cref="P:System.Windows.Controls.Primitives.RangeBase.SmallChange" />, to the right for a horizontal <see cref="T:System.Windows.Controls.Primitives.ScrollBar" /> or downward for a vertical <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />. For a vertical <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />, this movement occurs when the lower <see cref="T:System.Windows.Controls.Primitives.RepeatButton" /> is pressed or when the DOWN ARROW key is pressed, and corresponds to a <see cref="F:System.Windows.Controls.Primitives.ScrollBar.LineDownCommand" />. For a horizontal <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />, this movement occurs when the right <see cref="T:System.Windows.Controls.Primitives.RepeatButton" /> is pressed, and corresponds to a <see cref="F:System.Windows.Controls.Primitives.ScrollBar.LineRightCommand" />.</summary>
		// Token: 0x040030CF RID: 12495
		SmallIncrement,
		/// <summary>The <see cref="T:System.Windows.Controls.Primitives.Thumb" /> moved to a new position because the user selected Scroll Here in the shortcut menu of the <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />. This movement corresponds to the <see cref="F:System.Windows.Controls.Primitives.ScrollBar.ScrollHereCommand" />. To view the shortcut menu, right-click the mouse when the pointer is over the <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />. </summary>
		// Token: 0x040030D0 RID: 12496
		ThumbPosition,
		/// <summary>The <see cref="T:System.Windows.Controls.Primitives.Thumb" /> was dragged and caused a <see cref="E:System.Windows.UIElement.MouseMove" /> event. A <see cref="E:System.Windows.Controls.Primitives.ScrollBar.Scroll" /> event of this <see cref="T:System.Windows.Controls.Primitives.ScrollEventType" /> may occur more than one time when the <see cref="T:System.Windows.Controls.Primitives.Thumb" /> is dragged in the <see cref="T:System.Windows.Controls.Primitives.ScrollBar" />.</summary>
		// Token: 0x040030D1 RID: 12497
		ThumbTrack
	}
}
